//! 3D-printer G-code thumbnails. Slicers (PrusaSlicer / Cura / OrcaSlicer /
//! Bambu / SuperSlicer) embed one or more PNG previews as base64 inside comment
//! blocks near the top of the file:
//!
//! ```text
//! ; thumbnail begin 220x124 4500
//! ; iVBORw0KGgoAAAANSUhEUgAA...
//! ; ...more base64...
//! ; thumbnail end
//! ```
//!
//! We take the LARGEST block (best quality). Pure text scan + base64 — no
//! rendering, works on compact installs. Pairs with the `.3mf` extractor.

use base64::Engine;

/// Only scan the head — slicers always put thumbnails in the file's preamble.
const SCAN_LIMIT: usize = 4 * 1024 * 1024;

/// Extract the largest embedded PNG thumbnail from G-code text, or None.
pub fn extract(bytes: &[u8]) -> Option<Vec<u8>> {
    let head = &bytes[..bytes.len().min(SCAN_LIMIT)];
    // ASCII text; a binary file fails fast here (cheap bail for non-G-code).
    let text = std::str::from_utf8(head).ok()?;
    if !text.contains("thumbnail begin") {
        return None;
    }

    let mut best: Option<Vec<u8>> = None;
    let mut lines = text.lines();
    while let Some(line) = lines.next() {
        if !line.contains("thumbnail begin") {
            continue;
        }
        // Accumulate the base64 body until the matching "thumbnail end".
        let mut b64 = String::new();
        for l in lines.by_ref() {
            if l.contains("thumbnail end") {
                break;
            }
            b64.push_str(l.trim_start_matches(';').trim());
        }
        if let Ok(png) = base64::engine::general_purpose::STANDARD.decode(b64.trim()) {
            if png.starts_with(&[0x89, b'P', b'N', b'G'])
                && best.as_ref().map_or(true, |b| png.len() > b.len())
            {
                best = Some(png);
            }
        }
    }
    best
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extracts_largest_gcode_thumbnail() {
        // A real PNG, base64'd into a slicer-style comment block.
        let mut png = Vec::new();
        image::DynamicImage::ImageRgba8(image::RgbaImage::new(8, 8))
            .write_to(&mut std::io::Cursor::new(&mut png), image::ImageFormat::Png)
            .unwrap();
        let b64 = base64::engine::general_purpose::STANDARD.encode(&png);

        let mut gcode = String::from("; generated by PrusaSlicer\nM73 P0\n; thumbnail begin 16x16 999\n");
        for chunk in b64.as_bytes().chunks(78) {
            gcode.push_str("; ");
            gcode.push_str(std::str::from_utf8(chunk).unwrap());
            gcode.push('\n');
        }
        gcode.push_str("; thumbnail end\nG28\n");

        let got = extract(gcode.as_bytes()).expect("thumbnail");
        assert!(got.starts_with(&[0x89, b'P', b'N', b'G']));

        // Plain G-code with no thumbnail → None.
        assert!(extract(b"G28\nG1 X0 Y0\nM104 S200\n").is_none());
    }
}
