#![cfg(test)]

use super::render_page_counted;
use super::width_fitted_dims;
use super::{engine_can_open, render_pages_from_stream, PageFit, MAX_ENGINE_BYTES};
use super::{render_page_counted_path, PdfSession};

/// Build a minimal, valid multi-page PDF where page `i` is a solid `colours[i]`.
///
/// Hand-assembled rather than generated by ImageMagick, for the same reason
/// `container::djvu` builds its own: a fixture the TEST can produce runs in CI, where the
/// corpus is never checked out. A solid-colour page is also the only page whose rendered
/// output can be asserted exactly, which is what makes "page 3 really is page 3" provable
/// instead of eyeballed.
///
/// Deliberately NOT built with our own [`crate::topdf`] writer, which could do it. A
/// fixture written by the code under test shares its assumptions, so the pair would agree
/// with each other while both being wrong about PDF. These bytes are written to the spec
/// and read back by Windows' engine, so agreement means something.
///
/// US Letter at 72 dpi (612x792), one uncompressed content stream per page. The xref
/// offsets are computed as the body is written, because a PDF whose xref lies is a PDF
/// some readers accept and others silently refuse, and a fixture must not be the variable.
pub(super) fn solid_colour_pdf(colours: &[(u8, u8, u8)]) -> Vec<u8> {
    assert!(!colours.is_empty(), "a PDF needs at least one page");
    let n = colours.len();
    let mut out: Vec<u8> = Vec::new();
    let mut offsets: Vec<usize> = Vec::new();
    // Object numbering: 1 = catalog, 2 = page tree, then a (page, contents) pair each.
    let page_obj = |i: usize| 3 + i * 2;
    let obj = |out: &mut Vec<u8>, offsets: &mut Vec<usize>, body: String| {
        offsets.push(out.len());
        out.extend_from_slice(body.as_bytes());
    };

    out.extend_from_slice(b"%PDF-1.4\n");
    obj(
        &mut out,
        &mut offsets,
        "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n".into(),
    );
    let kids: Vec<String> = (0..n).map(|i| format!("{} 0 R", page_obj(i))).collect();
    obj(
        &mut out,
        &mut offsets,
        format!(
            "2 0 obj\n<< /Type /Pages /Kids [{}] /Count {n} >>\nendobj\n",
            kids.join(" ")
        ),
    );
    for (i, &(r, g, b)) in colours.iter().enumerate() {
        let (po, co) = (page_obj(i), page_obj(i) + 1);
        obj(
            &mut out,
            &mut offsets,
            format!(
                "{po} 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] \
                 /Contents {co} 0 R /Resources << >> >>\nendobj\n"
            ),
        );
        let stream = format!(
            "{:.5} {:.5} {:.5} rg\n0 0 612 792 re\nf\n",
            f32::from(r) / 255.0,
            f32::from(g) / 255.0,
            f32::from(b) / 255.0
        );
        obj(
            &mut out,
            &mut offsets,
            format!(
                "{co} 0 obj\n<< /Length {} >>\nstream\n{stream}endstream\nendobj\n",
                stream.len()
            ),
        );
    }

    let xref_at = out.len();
    let total = offsets.len() + 1; // +1 for the free object 0
    out.extend_from_slice(format!("xref\n0 {total}\n0000000000 65535 f \n").as_bytes());
    for off in &offsets {
        out.extend_from_slice(format!("{off:010} 00000 n \n").as_bytes());
    }
    out.extend_from_slice(
        format!("trailer\n<< /Size {total} /Root 1 0 R >>\nstartxref\n{xref_at}\n%%EOF\n")
            .as_bytes(),
    );
    out
}

/// Build a valid multi-page PDF where page `i` carries `headings[i]` in 48 pt and the same
/// line of ordinary 14 pt body text on every page.
///
/// The body line is the point of the fixture, not decoration. A 48 pt heading is legible at
/// almost any render width (it survives even at 200 px, see the table on
/// [`super::OCR_RENDER_WIDTH`]), so a heading-only fixture would keep passing while the width
/// fell far enough to stop reading real documents. The 14 pt line fails from 300 px down,
/// which is what makes this fixture able to fail at all.
///
/// It does NOT pin the width to its current value: 600 px reads this page perfectly well.
/// The argument for 2000 is about type sizes smaller than any fixture can prove from the
/// inside, and it lives on the constant.
///
/// Same hand-written-to-the-spec approach as [`solid_colour_pdf`], and the same reason: a
/// fixture produced by our own PDF writer would share its assumptions.
pub(super) fn text_pdf(headings: &[&str]) -> Vec<u8> {
    assert!(!headings.is_empty(), "a PDF needs at least one page");
    let n = headings.len();
    let mut out: Vec<u8> = Vec::new();
    let mut offsets: Vec<usize> = Vec::new();
    // 1 = catalog, 2 = page tree, 3 = the font, then a (page, contents) pair each. Written in
    // ascending object order so the xref built from `offsets` lines up by position.
    let page_obj = |i: usize| 4 + i * 2;
    let obj = |out: &mut Vec<u8>, offsets: &mut Vec<usize>, body: String| {
        offsets.push(out.len());
        out.extend_from_slice(body.as_bytes());
    };

    out.extend_from_slice(b"%PDF-1.4\n");
    obj(
        &mut out,
        &mut offsets,
        "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n".into(),
    );
    let kids: Vec<String> = (0..n).map(|i| format!("{} 0 R", page_obj(i))).collect();
    obj(
        &mut out,
        &mut offsets,
        format!(
            "2 0 obj\n<< /Type /Pages /Kids [{}] /Count {n} >>\nendobj\n",
            kids.join(" ")
        ),
    );
    // Helvetica is one of the 14 standard PDF fonts, so nothing has to be embedded and the
    // fixture stays a few kilobytes.
    obj(
        &mut out,
        &mut offsets,
        "3 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n".into(),
    );
    for (i, heading) in headings.iter().enumerate() {
        let (po, co) = (page_obj(i), page_obj(i) + 1);
        obj(
            &mut out,
            &mut offsets,
            format!(
                "{po} 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] \
                 /Contents {co} 0 R /Resources << /Font << /F1 3 0 R >> >> >>\nendobj\n"
            ),
        );
        let stream = format!(
            "BT /F1 48 Tf 60 640 Td ({heading}) Tj ET\n\
             BT /F1 14 Tf 60 560 Td ({BODY_LINE}) Tj ET\n"
        );
        obj(
            &mut out,
            &mut offsets,
            format!(
                "{co} 0 obj\n<< /Length {} >>\nstream\n{stream}endstream\nendobj\n",
                stream.len()
            ),
        );
    }

    let xref_at = out.len();
    let total = offsets.len() + 1;
    out.extend_from_slice(format!("xref\n0 {total}\n0000000000 65535 f \n").as_bytes());
    for off in &offsets {
        out.extend_from_slice(format!("{off:010} 00000 n \n").as_bytes());
    }
    out.extend_from_slice(
        format!("trailer\n<< /Size {total} /Root 1 0 R >>\nstartxref\n{xref_at}\n%%EOF\n")
            .as_bytes(),
    );
    out
}

/// The 14 pt line every page of [`text_pdf`] carries. A pangram, so the recognizer is asked
/// for a spread of letter shapes rather than one lucky word.
const BODY_LINE: &str = "the quick brown fox jumps over the lazy dog";

/// The whole Ctrl+F chain, end to end: an open session rasterizes a page, the in-box
/// recognizer reads it, and what comes back is that page's own words.
///
/// This is the test that would catch the feature rotting silently. Every part of the search
/// above this - the offsets, the page map, the progress note - is pure and unit-tested, and
/// all of it would keep passing perfectly while returning nothing at all, because the thing
/// that actually produces the text is two OS APIs talking to each other.
#[test]
fn body_text_survives_the_trip_through_a_rendered_page() {
    let headings = ["ALPHA", "BRAVO", "CHARLIE"];
    let pdf = text_pdf(&headings);
    let s = super::PdfSession::open(&pdf).expect("session opens");
    assert_eq!(s.page_count(), headings.len());

    let png = s
        .render_to_width(1, super::OCR_RENDER_WIDTH)
        .expect("page renders");
    let text = match crate::ocr::recognize_bytes(png) {
        Ok(t) => t,
        Err(e) => {
            // No OCR language pack on this machine. Say so loudly rather than passing
            // quietly: a green run that gated nothing is worse than a red one.
            eprintln!(
                "SKIPPED body_text_survives_the_trip_through_a_rendered_page: this machine \
                 has no usable OCR engine ({e:?}), so PDF text search cannot be gated here"
            );
            return;
        }
    };
    assert!(
        !text.trim().is_empty(),
        "the recognizer works but read nothing off a page of plain Helvetica"
    );
    let up = text.to_uppercase();
    assert!(
        up.contains("BRAVO"),
        "page 2's heading did not survive the round trip: {text:?}"
    );
    assert!(
        up.contains("QUICK") && up.contains("BROWN"),
        "14 pt body text did not survive at {} px, which is the width every PDF search \
         renders at. Anything at or below 300 px fails this line (see the table on \
         OCR_RENDER_WIDTH), so a width that dropped that far would silently return no \
         results for every real document: {text:?}",
        super::OCR_RENDER_WIDTH
    );

    // And every page must read as ITSELF. A search hit is turned into a page number, so a
    // page that reads as its neighbour scrolls the reader somewhere the word is not.
    for (i, want) in headings.iter().enumerate() {
        let png = s
            .render_to_width(i, super::OCR_RENDER_WIDTH)
            .unwrap_or_else(|| panic!("page {i} renders"));
        let got = crate::ocr::recognize_bytes(png)
            .unwrap_or_default()
            .to_uppercase();
        assert!(
            got.contains(want),
            "page {i} should carry {want}, read {got:?}"
        );
        for other in headings.iter().filter(|o| *o != want) {
            assert!(
                !got.contains(other),
                "page {i} also read as {other}, so pages are not distinguishable"
            );
        }
    }
}

/// Prints what the recognizer actually reads off a page at each render width, which is where
/// [`super::OCR_RENDER_WIDTH`]'s value comes from. Run by hand:
///
///   cargo test --lib what_the_recognizer_reads_at_each_render_width -- --ignored --nocapture
#[test]
#[ignore = "prints a measurement table"]
fn what_the_recognizer_reads_at_each_render_width() {
    let pdf = text_pdf(&["ALPHA"]);
    let s = super::PdfSession::open(&pdf).expect("session opens");
    eprintln!("  width   body px   heading   body      elapsed");
    for width in [200u32, 300, 400, 600, 800, 1000, 1600, 2000, 2400, 3200] {
        let t0 = std::time::Instant::now();
        let png = s.render_to_width(0, width).expect("renders");
        let text = crate::ocr::recognize_bytes(png).unwrap_or_default();
        let ms = t0.elapsed().as_millis();
        let up = text.to_uppercase();
        // 14 pt on a 612 pt page: how tall the body glyphs land once rendered at this width.
        let body_px = 14.0 * f64::from(width) / 612.0;
        eprintln!(
            "  {width:>5}   {body_px:>7.1}   {:<7}   {:<7}   {ms:>4} ms",
            if up.contains("ALPHA") { "yes" } else { "NO" },
            if up.contains("QUICK") && up.contains("BROWN") {
                "yes"
            } else {
                "NO"
            },
        );
    }
}

/// The four pages the corpus fixture and the unit tests both use. Page 0 is the corpus's
/// standard "right answer" blue, so the existing thumbnail colour gate covers this file
/// for free; the rest are far enough apart that no rounding can confuse them.
pub(super) const PAGES: [(u8, u8, u8); 4] =
    [(30, 60, 210), (30, 170, 60), (230, 140, 20), (140, 50, 190)];

/// Mean RGB of a decoded PNG, ignoring nothing. A solid page has no other content, so the
/// mean IS the colour, and a wrong page shows up as a channel miles away rather than a
/// subtle difference.
fn mean_rgb(png: &[u8]) -> (u8, u8, u8) {
    let img = image::load_from_memory(png)
        .expect("render output is a PNG")
        .to_rgb8();
    let (mut r, mut g, mut b) = (0u64, 0u64, 0u64);
    for p in img.pixels() {
        r += u64::from(p[0]);
        g += u64::from(p[1]);
        b += u64::from(p[2]);
    }
    let n = u64::from(img.width()) * u64::from(img.height());
    assert!(n > 0, "rendered page is empty");
    ((r / n) as u8, (g / n) as u8, (b / n) as u8)
}

fn close(a: (u8, u8, u8), b: (u8, u8, u8)) -> bool {
    let d = |x: u8, y: u8| i32::from(x) - i32::from(y);
    d(a.0, b.0).abs() <= 8 && d(a.1, b.1).abs() <= 8 && d(a.2, b.2).abs() <= 8
}

/// The gap that let a multi-page PDF bug ship: the corpus's only ordinary PDF has ONE page,
/// so nothing ever asked whether page N is really page N, or whether the page COUNT that
/// drives the viewer's pager is the document's real one.
#[test]
fn every_page_of_a_multipage_pdf_renders_as_itself() {
    let pdf = solid_colour_pdf(&PAGES);
    for (i, &want) in PAGES.iter().enumerate() {
        let Some((png, count)) = render_page_counted(&pdf, i as u32, 256) else {
            panic!("page {i} of a {}-page PDF did not render", PAGES.len());
        };
        assert_eq!(
            count as usize,
            PAGES.len(),
            "page {i} reported {count} pages; the viewer's pager reads this number"
        );
        let got = mean_rgb(&png);
        assert!(
            close(got, want),
            "page {i} rendered {got:?}, expected {want:?} - it drew a DIFFERENT page"
        );
    }
}

/// Asking past the end must clamp to the last page, never fail and never wrap. The viewer
/// relies on this: `goto_pdf_page` clamps too, but a restored session or a `--pdf-page`
/// argument can hand in any number at all.
#[test]
fn a_page_index_past_the_end_clamps_to_the_last_page() {
    let pdf = solid_colour_pdf(&PAGES);
    // Retried once, and only because `render_page_counted` folds a BUDGET expiry into the
    // same `None` a malformed document gets: on a loaded CI runner the whole suite shares
    // four cores and a scheduling spike past `PDF_TIMEOUT` read as a clamping failure
    // (2026-09-14, green on the rerun). A real clamping break returns a wrong page rather
    // than nothing, so the assertion below still fails deterministically.
    let (png, count) = render_page_counted(&pdf, 9_999, 256)
        .or_else(|| render_page_counted(&pdf, 9_999, 256))
        .expect("clamped render");
    assert_eq!(count as usize, PAGES.len());
    assert!(
        close(mean_rgb(&png), PAGES[PAGES.len() - 1]),
        "an out-of-range page must clamp to the LAST page"
    );
}

/// A single-page PDF must still report exactly one page, or the viewer would show a pager
/// for a document that has nothing to page through. This is the case the corpus already
/// covered, kept here so the pair is visible together.
#[test]
fn a_single_page_pdf_reports_one_page() {
    let pdf = solid_colour_pdf(&PAGES[..1]);
    let (_png, count) = render_page_counted(&pdf, 0, 128).expect("single-page render");
    assert_eq!(count, 1);
}

/// The session is what continuous scrolling stands on: it must know every page's size
/// BEFORE anything is rasterized, or the scroll bar would have to guess how tall the
/// document is and then jump as pages arrived.
#[test]
fn a_session_reports_every_page_size_without_rendering_anything() {
    let pdf = solid_colour_pdf(&PAGES);
    let s = super::PdfSession::open(&pdf).expect("session opens");
    assert_eq!(s.page_count(), PAGES.len());
    for i in 0..s.page_count() {
        let sz = s.size(i);
        // US Letter is 612x792 PDF points, and a point is 1/72 inch while a DIP is 1/96,
        // so WinRT reports 816x1056. Asserted in DIPs deliberately: the first version of
        // this test expected the point figures, and the only reason that mistake did not
        // reach the layout code is that it failed here.
        assert!(
            (sz.w - 816.0).abs() < 0.5 && (sz.h - 1056.0).abs() < 0.5,
            "page {i} reported {sz:?}, expected US Letter in DIPs (816x1056)"
        );
    }
}

/// One open document, many pages, each still its own page. The whole point of the session
/// is that the SECOND page does not re-parse the file, so a regression here would be
/// silent: correct pictures, just slow. The content assertion is what keeps it honest.
#[test]
fn a_session_renders_each_page_at_the_width_it_was_asked_for() {
    let pdf = solid_colour_pdf(&PAGES);
    let s = super::PdfSession::open(&pdf).expect("session opens");
    for (i, &want) in PAGES.iter().enumerate() {
        let png = s
            .render_to_width(i, 300)
            .unwrap_or_else(|| panic!("page {i} rendered"));
        let img = image::load_from_memory(&png).expect("PNG").to_rgb8();
        assert_eq!(img.width(), 300, "page {i} came back the wrong width");
        // 612x792 at 300 px wide is 388 tall; allow the rounding either way.
        assert!(
            (img.height() as i32 - 388).abs() <= 1,
            "page {i} is {}px tall, expected the page's own aspect",
            img.height()
        );
        assert!(
            close(mean_rgb(&png), want),
            "page {i} rendered the wrong page"
        );
    }
}

/// A session must refuse rather than mislead. An out-of-range page is `None`, not a
/// silently clamped neighbour: layout code asks by index and would otherwise stack the
/// last page over and over past the end of the document.
#[test]
fn a_session_refuses_a_page_that_does_not_exist() {
    let pdf = solid_colour_pdf(&PAGES);
    let s = super::PdfSession::open(&pdf).expect("session opens");
    assert!(s.render_to_width(PAGES.len(), 200).is_none());
    assert!(s.render_to_width(9_999, 200).is_none());
    assert!(
        s.render_to_width(0, 0).is_none(),
        "zero width is not a render"
    );
}

/// Garbage in, `None` out, and no hung thread. The viewer calls this on any file the user
/// presses Space on, so "not actually a PDF" is a normal input, not an exceptional one.
#[test]
fn a_session_declines_something_that_is_not_a_pdf() {
    assert!(super::PdfSession::open(b"this is not a PDF at all").is_none());
    assert!(super::PdfSession::open(&[]).is_none());
}

/// Writes a searchable multi-page PDF for driving the viewer headlessly, so a `--shot` of
/// Ctrl+F over a PDF is reproducible rather than depending on whatever file was to hand:
///
///   ST2K_FIXTURE_OUT=D:\tmp\searchable.pdf cargo test --lib write_searchable_pdf_fixture \
///     -- --ignored --nocapture
#[test]
#[ignore = "writes a searchable PDF fixture on demand"]
fn write_searchable_pdf_fixture() {
    let out = std::env::var("ST2K_FIXTURE_OUT").expect("set ST2K_FIXTURE_OUT to the path to write");
    // ST2K_FIXTURE_PAGES makes a document longer than the search's own page cap, which is
    // the only way to see the "read this many of that many pages" note stay up.
    let n: usize = std::env::var("ST2K_FIXTURE_PAGES")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(4);
    const NAMES: [&str; 8] = [
        "ALPHA", "BRAVO", "CHARLIE", "DELTA", "ECHO", "FOXTROT", "GOLF", "HOTEL",
    ];
    let owned: Vec<String> = (0..n.max(1))
        .map(|i| {
            if n <= NAMES.len() {
                NAMES[i].to_string()
            } else {
                format!("{} {}", NAMES[i % NAMES.len()], i + 1)
            }
        })
        .collect();
    let headings: Vec<&str> = owned.iter().map(String::as_str).collect();
    let pdf = text_pdf(&headings);
    std::fs::write(&out, &pdf).unwrap();
    eprintln!(
        "wrote {out} ({} bytes, {} pages)",
        pdf.len(),
        headings.len()
    );
}

/// Writes the corpus fixture. Run by hand after changing `PAGES`; `build-corpus.ps1`
/// documents the same command:
///
///   cargo test --release --lib write_pdf_corpus_fixture -- --ignored --nocapture
#[test]
#[ignore = "writes a corpus fixture on demand"]
fn write_pdf_corpus_fixture() {
    let corpus = crate::testcorpus::dir();
    assert!(corpus.is_dir(), "no test-corpus at {}", corpus.display());
    let pdf = solid_colour_pdf(&PAGES);
    let p = corpus.join("sample-multipage.pdf");
    std::fs::write(&p, &pdf).unwrap();
    eprintln!(
        "wrote {} ({} bytes, {} pages)",
        p.display(),
        pdf.len(),
        PAGES.len()
    );
}

/// The continuous view renders a page at a fixed WIDTH, and the page's aspect comes from the
/// file: a legal 1 x 14400 pt strip asked for at 1000 px wide wanted a 14.4-million-row bitmap.
/// Both edges are capped at `MAX_DIM`, and an ordinary page is drawn exactly as asked.
#[test]
fn a_width_fitted_page_never_passes_max_dim() {
    let cap = crate::decode::limits::MAX_DIM;
    let (w, h) = width_fitted_dims(1.0, 14_400.0, 1000);
    assert!(w >= 1 && h == cap, "{w} x {h}");
    assert_eq!(width_fitted_dims(612.0, 792.0, 1000), (1000, 1294));
    let (w, h) = width_fitted_dims(612.0, 792.0, 100_000);
    assert!(w <= cap && h <= cap, "{w} x {h}");
}

/// A page rendered by PATH (the rasterizer reading the file itself, as Quick preview does so a
/// PDF past the input ceiling still opens) is the page rendered from the same file's bytes, and
/// a session opened by path lays out the same pages.
#[test]
fn a_pdf_read_by_path_renders_as_its_bytes_do() {
    for name in ["real.pdf", "real.ai"] {
        let (Some(path), Some(bytes)) =
            (crate::testcorpus::path(name), crate::testcorpus::read(name))
        else {
            eprintln!("NOT MEASURED: {name} absent");
            continue;
        };
        let path = path.to_string_lossy().into_owned();
        let (a, n) = render_page_counted(&bytes, 0, 300).expect("from bytes");
        let (b, m) = render_page_counted_path(&path, 0, 300).expect("by path");
        assert_eq!(n, m, "{name}: page count");
        let (a, b) = (
            image::load_from_memory(&a).unwrap().to_rgba8(),
            image::load_from_memory(&b).unwrap().to_rgba8(),
        );
        assert!(a == b, "{name}: the two renders differ");
        let session = PdfSession::open_path(&path).expect("session by path");
        assert_eq!(session.page_count(), n as usize, "{name}");
    }
}

/// Windows' PDF engine crashes the process on a document past 2 GiB, so none is handed to it:
/// the stream render refuses on the declared size alone, before it reads a byte (the stream here
/// is a real, small PDF, which would render if the size were not checked first).
#[test]
fn a_pdf_past_two_gib_is_never_handed_to_the_engine() {
    assert!(engine_can_open(MAX_ENGINE_BYTES));
    assert!(!engine_can_open(MAX_ENGINE_BYTES + 1));
    assert!(!engine_can_open(2253 << 20), "the gate's 2.2 GB twin");
    let Some(bytes) = crate::testcorpus::read("real.pdf") else {
        eprintln!("NOT MEASURED: real.pdf absent");
        return;
    };
    use windows::Win32::System::Com::{CoInitializeEx, COINIT_APARTMENTTHREADED};
    // The render hands the stream to its worker through the Global Interface Table.
    let _ = unsafe { CoInitializeEx(None, COINIT_APARTMENTTHREADED) };
    let stream = unsafe { windows::Win32::UI::Shell::SHCreateMemStream(Some(&bytes)) }
        .expect("SHCreateMemStream");
    let fit = PageFit::LongSide(256);
    assert!(render_pages_from_stream(&stream, bytes.len() as u64, fit, 1).is_some());
    assert!(render_pages_from_stream(&stream, MAX_ENGINE_BYTES + 1, fit, 1).is_none());
}
