//! Reading only the head of a file that keeps its preview there.
//! PSD, DWG, G-code and CLIP all put something usable near the front, so a
//! capped read rescues a file that would otherwise be too big to open.

use super::*;

#[test]
fn read_preview_capped_rescues_head_preview_containers() {
    // Over the cap + BLENDER magic -> a bounded prefix; over the cap without the
    // magic -> the hard refusal; under the cap -> the whole file. Caps shrunk via
    // the `_at` variant so the test doesn't stage multi-hundred-MB files.
    let dir = std::env::temp_dir().join(format!("st2k_head_preview_test_{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();

    let blend = dir.join("big.blend");
    let mut data = b"BLENDER-v277".to_vec();
    data.resize(2048, 0);
    std::fs::write(&blend, &data).unwrap();
    let got = read_preview_capped_at(blend.to_str().unwrap(), 1024, 1536).unwrap();
    assert_eq!(
        got.len(),
        1536,
        "oversized blend must yield the bounded prefix"
    );
    assert!(got.starts_with(b"BLENDER"));

    // Prefix cap larger than the file: return everything there is.
    let got = read_preview_capped_at(blend.to_str().unwrap(), 1024, 8192).unwrap();
    assert_eq!(got.len(), 2048);

    let plain = dir.join("big.jpg");
    let mut data = vec![0xFFu8, 0xD8, 0xFF, 0xE0];
    data.resize(2048, 0);
    std::fs::write(&plain, &data).unwrap();
    assert!(
        read_preview_capped_at(plain.to_str().unwrap(), 1024, 1536).is_err(),
        "oversized non-head-preview file keeps the hard refusal"
    );

    // Under the cap: identical to read_capped (whole file, any format).
    let got = read_preview_capped_at(plain.to_str().unwrap(), 4096, 1536).unwrap();
    assert_eq!(got.len(), 2048);
}

#[test]
fn read_preview_capped_under_cap_psd_reads_only_the_head() {
    // UNDER-cap opaque PSD with a baked thumbnail and a fat layer-data tail:
    // the fast path returns the exact head prefix. The same document without
    // the thumbnail, or with alpha, falls back to the whole file.
    let dir = std::env::temp_dir().join(format!("st2k_psd_head_fast_test_{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();

    let (psd, head_len) = crate::container::psd_testutil::synthetic_psd(3, true, 512 * 1024);
    let path = dir.join("big.psd");
    std::fs::write(&path, &psd).unwrap();
    let got = read_preview_capped_at(path.to_str().unwrap(), 100 << 20, 16 << 20).unwrap();
    assert_eq!(
        got.len(),
        head_len,
        "opaque PSD must read only the head prefix"
    );
    assert_eq!(got, &psd[..head_len]);

    let (bare, _) = crate::container::psd_testutil::synthetic_psd(3, false, 64 * 1024);
    let path = dir.join("bare.psd");
    std::fs::write(&path, &bare).unwrap();
    let got = read_preview_capped_at(path.to_str().unwrap(), 100 << 20, 16 << 20).unwrap();
    assert_eq!(got.len(), bare.len(), "no baked thumbnail -> whole file");

    let (alpha, _) = crate::container::psd_testutil::synthetic_psd(4, true, 64 * 1024);
    let path = dir.join("alpha.psd");
    std::fs::write(&path, &alpha).unwrap();
    let got = read_preview_capped_at(path.to_str().unwrap(), 100 << 20, 16 << 20).unwrap();
    assert_eq!(
        got.len(),
        alpha.len(),
        "transparent PSD -> whole file for the composite"
    );
}

#[test]
fn read_preview_capped_under_cap_dwg_and_gcode_read_only_the_head() {
    let dir = std::env::temp_dir().join(format!("st2k_head_fast_more_test_{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();

    // DWG: exact prefix = through the preview record's payload.
    let (dwg, head_len) = crate::container::dwg_testutil::synthetic_dwg(true, 512 * 1024);
    let path = dir.join("big.dwg");
    std::fs::write(&path, &dwg).unwrap();
    let got = read_preview_capped_at(path.to_str().unwrap(), 100 << 20, 16 << 20).unwrap();
    assert_eq!(
        got.len(),
        head_len,
        "DWG must read only through the preview record"
    );

    // G-code: the fast path is keyed on EXTENSION (no magic bytes) and uses
    // gcode::SCAN_LIMIT, which the extractor already clamps to — so the
    // shortened read must be byte-identical in RESULT to the whole file.
    let mut png = Vec::new();
    image::DynamicImage::ImageRgba8(image::RgbaImage::new(8, 8))
        .write_to(&mut std::io::Cursor::new(&mut png), image::ImageFormat::Png)
        .unwrap();
    let b64 = base64::Engine::encode(&base64::engine::general_purpose::STANDARD, &png);
    let mut g = String::from("; generated by PrusaSlicer\n; thumbnail begin 16x16 999\n");
    for chunk in b64.as_bytes().chunks(78) {
        g.push_str("; ");
        g.push_str(std::str::from_utf8(chunk).unwrap());
        g.push('\n');
    }
    g.push_str("; thumbnail end\n");
    let head_bytes = g.len();
    // ~5 MB of toolpath behind the preview, pushing the file past SCAN_LIMIT.
    g.push_str(&"G1 X10 Y10 E1\n".repeat(380_000));
    let path = dir.join("big.gcode");
    std::fs::write(&path, g.as_bytes()).unwrap();
    assert!(std::fs::metadata(&path).unwrap().len() > (4 << 20) + head_bytes as u64);
    let got = read_preview_capped_at(path.to_str().unwrap(), 100 << 20, 16 << 20).unwrap();
    assert_eq!(
        got.len(),
        4 << 20,
        "G-code must read only gcode::SCAN_LIMIT"
    );
    assert!(
        crate::container::extract_cover(&got).is_some(),
        "the SCAN_LIMIT prefix must still yield the slicer thumbnail"
    );

    // A SMALL G-code file (under SCAN_LIMIT) gets the ordinary whole read —
    // the prefix would not be smaller, so the fast path declines.
    let small = dir.join("small.gcode");
    let body = b"G28\nG1 X0 Y0\n";
    std::fs::write(&small, body).unwrap();
    let got = read_preview_capped_at(small.to_str().unwrap(), 100 << 20, 16 << 20).unwrap();
    assert_eq!(got.len(), body.len());
}

#[test]
fn read_preview_capped_rescues_oversized_clip() {
    // A .clip past the byte cap must yield its embedded preview PNG via the
    // tail-database seek (the CLI twin of the provider's IStream rescue) —
    // not the hard refusal, and not a head prefix (the preview is NOT in
    // the head; the db sits after the layer-data padding).
    let dir = std::env::temp_dir().join(format!("st2k_clip_preview_test_{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    let png = [0x89u8, b'P', b'N', b'G', 42, 42, 42, 42];
    let clip = crate::container::clip_testutil::synthetic_clip(&png, 64 * 1024, false);
    let path = dir.join("big.clip");
    std::fs::write(&path, &clip).unwrap();
    let got = read_preview_capped_at(path.to_str().unwrap(), 1024, 1536).unwrap();
    assert_eq!(got, &png[..]);
}
