//! Measure what Microsoft's AV1 WIC codec actually does with colour, on THIS machine, now.
//!
//! # Why this exists
//!
//! Issue #9 was diagnosed on 2026-08-04 by measuring the AV1 Video Extension by hand and
//! writing the answers into a table in [`super::color`]: an 8-bit BT.709 AVIF was decoded
//! correctly, everything else was not, so everything else paid for an ImageMagick subprocess.
//!
//! That table was a measurement of ONE build of a Microsoft Store component that updates
//! itself. It went stale in five weeks. Re-measured on 2026-09-08 against extension
//! **2.0.30.0** (the table was written against 2.0.24.0), with dav1d and ImageMagick as the
//! two independent opinions, worst channel error out of 255:
//!
//! | class | 2.0.24.0 | 2.0.30.0 | what the old table did with it |
//! |---|---|---|---|
//! | 8-bit, `nclx` BT.709 | 1 | **23** | trusted it — so every ordinary web AVIF shifted |
//! | 8-bit, `nclx` BT.601 | 39 | 39 | routed around it (right, by luck of it not changing) |
//! | 8-bit, no `colr` box | 39 | **1** | routed around it — a subprocess for nothing |
//! | 10-bit, `nclx` BT.601 | 11 | 11 | curve-corrected (right) |
//! | 10-bit, `nclx` BT.709 | 11 | **27** | curve-corrected, leaving 13 behind |
//! | 10-bit, monochrome | not measured | **0** | curve-corrected a CORRECT decode, to 15 wrong |
//!
//! Four of six classes wrong, in the direction that matters: the 8-bit BT.709 row is most of
//! the AVIF on the web, and it is exactly the "some of my thumbnails have shifted colours"
//! the reporter came back about. The old comment claimed a whitelist meant "a WIC version that
//! changes its behaviour cannot silently reintroduce the bug". It cannot introduce it for a
//! shape we never trusted; it did precisely that for the one shape we did.
//!
//! # What this does instead
//!
//! Six AVIF files, ~360 bytes each, are compiled into the binary. Each is four flat patches
//! whose correct sRGB values we know, encoded LOSSLESS in 4:4:4 so the only error a probe can
//! possibly measure is the decoder's. On the first AVIF of the process each one is decoded
//! through the very WIC path the tier would use, and the answer is compared with what it
//! should be:
//!
//! * within [`TOLERANCE`] -> [`AvifWicVerdict::Trusted`], take the cheap in-process path
//! * wrong, but right after [`super::color::undo_wic_high_depth_curve`] -> that correction
//! * wrong either way -> [`AvifWicVerdict::Untrusted`], pay for ImageMagick
//!
//! So the curve case is DISCOVERED rather than assumed, and the next extension update is
//! measured on the machine it lands on instead of waiting for a bug report. If WIC cannot
//! decode a probe at all (N/KN editions, the extension not installed), that class reads
//! Untrusted, which routes to ImageMagick where one exists and falls back to WIC where it does
//! not — the Compact install's behaviour today, unchanged.
//!
//! The probes are regenerated by `scripts/make-wic-probes.py`; `assets/wicprobe/README.md`
//! says how and why they are shaped the way they are.

use super::*;

/// Worst per-channel error, out of 255, still counted as "this decoder is right".
///
/// Every correct class measures at or under 1 and every wrong one at or over 11, so the line
/// sits in a gap ten wide rather than on a threshold anyone has to defend. It has to be at
/// least 1 because the probes are encoded from 8-bit sources through a YUV matrix, and that
/// round trip is not bit-exact even losslessly.
const TOLERANCE: f32 = 4.0;

/// The probe images: 32x32, four 16x16 flat patches, lossless 4:4:4.
const P8_BT709: &[u8] = include_bytes!("../../assets/wicprobe/avif-8bit-bt709.avif");
const P8_BT601: &[u8] = include_bytes!("../../assets/wicprobe/avif-8bit-bt601.avif");
const P8_NOCOLR: &[u8] = include_bytes!("../../assets/wicprobe/avif-8bit-nocolr.avif");
const P10_BT709: &[u8] = include_bytes!("../../assets/wicprobe/avif-10bit-bt709.avif");
const P10_BT601: &[u8] = include_bytes!("../../assets/wicprobe/avif-10bit-bt601.avif");
const P10_MONO: &[u8] = include_bytes!("../../assets/wicprobe/avif-10bit-mono.avif");

/// What the four patches of a colour probe must come back as, in sRGB.
///
/// Saturated red and green move under a YUV MATRIX error while the mid grey does not, which is
/// what separates a matrix fault from a range or transfer one; the skin tone is the patch a
/// human would notice first, and it is here so the tolerance is defended against a real colour
/// rather than only against primaries.
const EXPECT_COLOUR: [[u8; 3]; 4] = [[255, 0, 0], [0, 255, 0], [128, 128, 128], [222, 178, 145]];

/// The monochrome probe's four greys.
const EXPECT_MONO: [[u8; 3]; 4] = [[32, 32, 32], [96, 96, 96], [160, 160, 160], [224, 224, 224]];

/// The colour-signalling classes Windows has ever treated differently from one another.
///
/// One probe each. Splitting BT.709 from BT.601 is not fussiness: those two rows have swapped
/// places between extension versions, which is the whole reason this file exists.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum WicClass {
    /// 8-bit with an `nclx` box naming BT.709 or the identity matrix.
    EightBt709,
    /// 8-bit with an `nclx` box naming a BT.601 matrix — what `avifenc` writes by default.
    EightBt601,
    /// 8-bit with no `colr` box at all, so the decoder is guessing.
    EightNoColr,
    /// 10/12-bit with an `nclx` box naming BT.709 or the identity matrix.
    HighBt709,
    /// 10/12-bit with an `nclx` box naming a BT.601 matrix.
    HighBt601,
    /// 10/12-bit monochrome (`av1C`'s monochrome flag), where there is no matrix to get wrong.
    HighMono,
}

impl WicClass {
    fn probe(self) -> (&'static [u8], &'static [[u8; 3]; 4]) {
        match self {
            Self::EightBt709 => (P8_BT709, &EXPECT_COLOUR),
            Self::EightBt601 => (P8_BT601, &EXPECT_COLOUR),
            Self::EightNoColr => (P8_NOCOLR, &EXPECT_COLOUR),
            Self::HighBt709 => (P10_BT709, &EXPECT_COLOUR),
            Self::HighBt601 => (P10_BT601, &EXPECT_COLOUR),
            Self::HighMono => (P10_MONO, &EXPECT_MONO),
        }
    }

    fn index(self) -> usize {
        match self {
            Self::EightBt709 => 0,
            Self::EightBt601 => 1,
            Self::EightNoColr => 2,
            Self::HighBt709 => 3,
            Self::HighBt601 => 4,
            Self::HighMono => 5,
        }
    }

    /// Every class, so the measurement pass and its test can iterate without a hand-kept list.
    pub(super) const ALL: [WicClass; 6] = [
        Self::EightBt709,
        Self::EightBt601,
        Self::EightNoColr,
        Self::HighBt709,
        Self::HighBt601,
        Self::HighMono,
    ];
}

/// How far this machine's WIC can be trusted with each class. Measured once per process.
///
/// A `OnceLock` rather than a retrying cache because the only caller reaches here from the
/// decode tier, on a thread that is about to use WIC anyway and therefore has COM up; a probe
/// that fails there would fail for the real file too, and Untrusted is the right answer for
/// both.
///
/// LOAD-BEARING: nothing [`measure`] calls may reach back into this function. `wic_fallback` is
/// the raw codec path and does not consult a verdict (only `decode::route_isobmff_wic_quirks`
/// does, above it), and `undo_wic_high_depth_curve` is a pure lookup table. Re-entering
/// `get_or_init` deadlocks, so if a future tier starts routing inside `wic_fallback`, this has
/// to stop being a `OnceLock`.
fn trust() -> &'static [AvifWicVerdict; 6] {
    static TRUST: std::sync::OnceLock<[AvifWicVerdict; 6]> = std::sync::OnceLock::new();
    TRUST.get_or_init(|| {
        let mut out = [AvifWicVerdict::Untrusted; 6];
        for class in WicClass::ALL {
            out[class.index()] = measure(class);
        }
        crate::safety::log_debugf!(
            "decode: WIC AVIF colour probe: 8/709={:?} 8/601={:?} 8/none={:?} \
             hi/709={:?} hi/601={:?} hi/mono={:?}",
            out[0],
            out[1],
            out[2],
            out[3],
            out[4],
            out[5]
        );
        out
    })
}

/// This machine's verdict for `class`.
pub(super) fn verdict_for(class: WicClass) -> AvifWicVerdict {
    trust()[class.index()]
}

/// Decode one probe through WIC and grade the answer.
fn measure(class: WicClass) -> AvifWicVerdict {
    let (bytes, expect) = class.probe();
    let Ok(img) = wic::wic_fallback(bytes, None) else {
        // No AV1 codec on this machine (N/KN edition, extension not installed) — the file
        // itself would not decode either, so nothing downstream changes.
        return AvifWicVerdict::Untrusted;
    };
    if worst_error(&img, expect).is_some_and(|e| e <= TOLERANCE) {
        return AvifWicVerdict::Trusted;
    }
    // Not right as handed over. Is it right after the one correction we can apply? Running the
    // production function rather than re-deriving its curve here is deliberate: this then tests
    // the correction that will actually run, so the two cannot drift apart.
    let corrected = color::undo_wic_high_depth_curve(img);
    if worst_error(&corrected, expect).is_some_and(|e| e <= TOLERANCE) {
        return AvifWicVerdict::NeedsHighDepthCurve;
    }
    AvifWicVerdict::Untrusted
}

/// Worst per-channel difference between a decoded probe and what it should be.
///
/// `None` when the image is not the shape a probe must be, which is itself a failure: a decoder
/// that hands back the wrong size has not passed, so the caller treats it as untrusted.
fn worst_error(img: &DynamicImage, expect: &[[u8; 3]; 4]) -> Option<f32> {
    let rgb = img.to_rgb8();
    let (w, h) = rgb.dimensions();
    if w < 32 || h < 32 {
        return None;
    }
    let (qw, qh) = (w / 2, h / 2);
    let mut worst = 0.0f32;
    for (i, want) in expect.iter().enumerate() {
        let (row, col) = (i as u32 / 2, i as u32 % 2);
        // The middle half of each quadrant: away from every patch edge, so a decoder that
        // blurs across the boundary is not scored on the blur.
        let (x0, y0) = (col * qw + qw / 4, row * qh + qh / 4);
        let (mut sum, mut n) = ([0u32; 3], 0u32);
        for y in y0..y0 + qh / 2 {
            for x in x0..x0 + qw / 2 {
                let px = rgb.get_pixel(x, y).0;
                for c in 0..3 {
                    sum[c] += u32::from(px[c]);
                }
                n += 1;
            }
        }
        if n == 0 {
            return None;
        }
        for c in 0..3 {
            let mean = sum[c] as f32 / n as f32;
            worst = worst.max((mean - f32::from(want[c])).abs());
        }
    }
    Some(worst)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The probes must be present and shaped like AVIF, whatever this machine can decode.
    /// A build that lost one of them would otherwise only show up as "everything is untrusted",
    /// i.e. quietly slow rather than broken.
    #[test]
    fn every_class_has_a_real_avif_probe() {
        for class in WicClass::ALL {
            let (bytes, _) = class.probe();
            assert!(
                bytes.len() > 100,
                "{class:?} probe is {} bytes, which is not a file",
                bytes.len()
            );
            assert_eq!(
                bytes.get(4..8),
                Some(&b"ftyp"[..]),
                "{class:?} probe is not ISOBMFF"
            );
            assert!(
                bytes.windows(4).any(|w| w == b"av1C"),
                "{class:?} probe carries no AV1 configuration box"
            );
        }
    }

    /// Exactly one probe per class, and no two classes sharing a slot.
    #[test]
    fn class_indices_are_distinct() {
        let mut seen = [false; 6];
        for class in WicClass::ALL {
            assert!(!seen[class.index()], "{class:?} reuses a slot");
            seen[class.index()] = true;
        }
        assert!(seen.iter().all(|s| *s));
    }

    /// The no-`colr` probe must really have no colour box: it is generated by renaming the box
    /// in an otherwise identical file, and a generation slip would make it a duplicate of the
    /// BT.709 probe while still decoding fine.
    #[test]
    fn the_nocolr_probe_carries_no_colour_box() {
        assert!(
            !P8_NOCOLR.windows(4).any(|w| w == b"colr"),
            "the no-colr probe still has a colr box"
        );
        for (name, bytes) in [
            ("8-bit BT.709", P8_BT709),
            ("8-bit BT.601", P8_BT601),
            ("10-bit BT.709", P10_BT709),
            ("10-bit BT.601", P10_BT601),
            ("10-bit mono", P10_MONO),
        ] {
            assert!(
                bytes.windows(4).any(|w| w == b"colr"),
                "the {name} probe should carry a colr box"
            );
        }
    }

    /// Grading is what decides whether a machine pays for a subprocess, so it gets a test that
    /// does not need a codec: a synthetic "decode" that is exactly right, and one that is off
    /// by more than the tolerance on a single patch.
    #[test]
    fn grading_separates_a_right_answer_from_a_wrong_one() {
        let mut img = image::RgbImage::new(32, 32);
        for (i, want) in EXPECT_COLOUR.iter().enumerate() {
            let (row, col) = (i / 2, i % 2);
            for y in row * 16..row * 16 + 16 {
                for x in col * 16..col * 16 + 16 {
                    img.put_pixel(x as u32, y as u32, image::Rgb(*want));
                }
            }
        }
        let exact = DynamicImage::ImageRgb8(img.clone());
        assert_eq!(worst_error(&exact, &EXPECT_COLOUR), Some(0.0));

        // Shift the grey patch by 20: a matrix error leaves greys alone, so this is the shape
        // of a RANGE error and must not pass.
        for y in 16..32 {
            for x in 0..16 {
                img.put_pixel(x, y, image::Rgb([148, 148, 148]));
            }
        }
        let off = DynamicImage::ImageRgb8(img);
        assert!(worst_error(&off, &EXPECT_COLOUR).is_some_and(|e| e > TOLERANCE));
    }

    /// A decoder that hands back something that is not the probe's shape has not passed.
    #[test]
    fn a_wrong_sized_decode_is_not_a_pass() {
        let tiny = DynamicImage::ImageRgb8(image::RgbImage::new(8, 8));
        assert_eq!(worst_error(&tiny, &EXPECT_COLOUR), None);
    }
}
