#!/usr/bin/env python3
"""Write the format badge's letter outlines (`src/badge/font.rs`) from DejaVu Sans Condensed Bold.

WHY THIS EXISTS
---------------
The corner badge used to draw a 5x7 pixel font scaled by a whole number. Explorer then resizes
the 256 px tile to the size it shows (144 px at 150 % scaling), and a pixel font resized by 0.56
comes out jagged AND blurry at once (issue #50). Outlines rasterised with anti-aliasing at the
exact size the badge needs survive that resize the way any text in a picture does.

The outlines are compiled into the DLL as data and drawn with tiny-skia, which the SVG
thumbnails already link, so the badge still needs no GDI, no font file at run time and no
system font: it renders byte-for-byte the same on every machine, which is why it never used
DrawText in the first place.

WHY DEJAVU SANS CONDENSED BOLD
------------------------------
Drawn for screens, heavy strokes that survive a downscale, narrow caps so a four-letter label
fits the corner. The Bitstream Vera licence lets the outlines ship inside software as long as
the copyright notice travels with them (`assets/fonts/LICENSE-DejaVu.txt`). Only the 37
characters a format label can contain are kept: A-Z, 0-9 and `+`.

Re-run only to change the font or the character set:

    python scripts/build-badge-font.py --src <path to DejaVuSansCondensed-Bold.ttf>
    python scripts/build-badge-font.py        # downloads the DejaVu 2.37 release

Needs `fonttools` (`pip install -r scripts/requirements-dev.txt`). The generated file is
COMMITTED, so a build and CI never need this script or the network.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import sys
import urllib.request
import zipfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "src" / "badge" / "font.rs"
OUT_LICENSE = REPO / "assets" / "fonts" / "LICENSE-DejaVu.txt"

UPSTREAM = "https://github.com/dejavu-fonts/dejavu-fonts/releases/download/version_2_37/dejavu-fonts-ttf-2.37.zip"
MEMBER = "dejavu-fonts-ttf-2.37/ttf/DejaVuSansCondensed-Bold.ttf"
LICENSE_MEMBER = "dejavu-fonts-ttf-2.37/LICENSE"
TTF_SHA256 = "38098d0b8edd8430a0f53fb2831b5d36037563a998a620d3c87a4d7591766d20"

# Every character `badge::label_for` accepts, in the order `font::GLYPHS` stores them.
CHARSET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+"


def load(src: str | None) -> tuple[bytes, bytes | None]:
    """The TTF bytes (sha-checked) and, when downloaded, the licence text beside it."""
    if src:
        data = Path(src).read_bytes()
        lic = Path(src).resolve().parent.parent / "LICENSE"
        licence = lic.read_bytes() if lic.exists() else None
    else:
        with urllib.request.urlopen(UPSTREAM) as r:  # nosec B310 - fixed https URL
            z = zipfile.ZipFile(io.BytesIO(r.read()))
        data = z.read(MEMBER)
        licence = z.read(LICENSE_MEMBER)
    got = hashlib.sha256(data).hexdigest()
    if got != TTF_SHA256:
        sys.exit(f"DejaVuSansCondensed-Bold.ttf sha256 {got}, expected {TTF_SHA256}")
    return data, licence


def outlines(data: bytes):
    """(cap height, [(char, advance, segments)]) in font units, with TrueType's implied
    on-curve points made explicit, so every curve is one quadratic."""
    from fontTools.pens.basePen import BasePen
    from fontTools.ttLib import TTFont

    class Rec(BasePen):
        def __init__(self, glyphset):
            super().__init__(glyphset)
            self.segs: list[tuple] = []

        def _moveTo(self, p):
            self.segs.append(("M", p))

        def _lineTo(self, p):
            self.segs.append(("L", p))

        def _qCurveToOne(self, c, p):
            self.segs.append(("Q", c, p))

        def _curveToOne(self, c1, c2, p):
            raise SystemExit("cubic outline in a TrueType font")

        def _closePath(self):
            self.segs.append(("Z",))

    font = TTFont(io.BytesIO(data))
    cmap = font.getBestCmap()
    gs = font.getGlyphSet()
    cap = font["glyf"][cmap[ord("H")]].yMax
    out = []
    for ch in CHARSET:
        name = cmap[ord(ch)]
        pen = Rec(gs)
        gs[name].draw(pen)
        out.append((ch, font["hmtx"][name][0], pen.segs))
    return cap, out


def rust_seg(seg) -> str:
    r = lambda p: f"{round(p[0])}, {round(p[1])}"  # noqa: E731 - one-line formatter
    if seg[0] == "M":
        return f"M({r(seg[1])})"
    if seg[0] == "L":
        return f"L({r(seg[1])})"
    if seg[0] == "Q":
        return f"Q({r(seg[1])}, {r(seg[2])})"
    return "Z"


def write(cap: int, glyphs) -> str:
    lines = [
        "//! Letter outlines for the format badge: DejaVu Sans Condensed Bold 2.37, the 37",
        "//! characters a label can hold. GENERATED by `scripts/build-badge-font.py`; do not edit.",
        "//! Fonts (c) Bitstream, DejaVu changes public domain: `assets/fonts/LICENSE-DejaVu.txt`.",
        "",
        "/// One outline step in font units, y up: move, line, quadratic (control, end), close.",
        "#[derive(Clone, Copy)]",
        "pub(super) enum Seg {",
        "    M(i16, i16),",
        "    L(i16, i16),",
        "    Q(i16, i16, i16, i16),",
        "    Z,",
        "}",
        "",
        "/// A character's advance width and outline, in font units.",
        "pub(super) struct Glyph {",
        "    pub(super) advance: i16,",
        "    pub(super) segs: &'static [Seg],",
        "}",
        "",
        "/// The top of a flat capital (`H`), so a label can be sized by its cap height.",
        f"pub(super) const CAP_HEIGHT: f32 = {cap}.0;",
        "",
        "/// The characters [`GLYPHS`] holds, in the same order.",
        f'const CHARSET: &[u8] = b"{CHARSET}";',
        "",
        "/// The outline for `c`, or `None` for a character the badge cannot draw.",
        "pub(super) fn glyph(c: u8) -> Option<&'static Glyph> {",
        "    CHARSET.iter().position(|&x| x == c).map(|i| &GLYPHS[i])",
        "}",
        "",
        "use Seg::{L, M, Q, Z};",
        "",
        "#[rustfmt::skip]",
        f"static GLYPHS: [Glyph; {len(glyphs)}] = [",
    ]
    for ch, adv, segs in glyphs:
        lines.append(f"    // {ch}")
        lines.append(f"    Glyph {{ advance: {adv}, segs: &[")
        row = "        "
        for s in segs:
            piece = rust_seg(s) + ", "
            if len(row) + len(piece) > 99:
                lines.append(row.rstrip())
                row = "        "
            row += piece
        if row.strip():
            lines.append(row.rstrip())
        lines.append("    ] },")
    lines.append("];")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--src", help="local DejaVuSansCondensed-Bold.ttf (from the 2.37 release)")
    args = ap.parse_args()
    try:
        import fontTools  # noqa: F401
    except ImportError:
        print("needs fonttools:  pip install -r scripts/requirements-dev.txt", file=sys.stderr)
        return 2
    data, licence = load(args.src)
    cap, glyphs = outlines(data)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(write(cap, glyphs), encoding="utf-8", newline="\n")
    if licence:
        OUT_LICENSE.parent.mkdir(parents=True, exist_ok=True)
        OUT_LICENSE.write_bytes(licence)
    print(f"{OUT.relative_to(REPO)}: {len(glyphs)} glyphs, {sum(len(g[2]) for g in glyphs)} segments")
    return 0


if __name__ == "__main__":
    sys.exit(main())
