<#
  check-dicom.ps1 — CONTENT guard for the .dcm decode path (src/decode.rs:
  looks_like_dicom -> `dcm:-` + `-auto-level`). The corpus regression only checks
  that a .dcm produces *some* non-empty thumbnail; this asserts the pixels are
  actually RIGHT, so a silent colour/contrast regression fails the gate.

  Renders two committed synthetic fixtures (tests\fixtures\dicom, generated by
  make_fixtures.py — never real patient data) via st2k and checks:

    color_stripes.dcm  six known hue stripes survive -auto-level. The load-bearing
                       one is the warm 'gold' stripe: default -auto-level scales all
                       channels TOGETHER (hue-preserving); a per-channel regression
                       would cool/neutralise gold. Also checks red/green/blue each
                       keep their dominant channel.
    mono1_grad.dcm     MONOCHROME1 (0=white) renders white->black L->R, i.e. magick
                       applied the inversion (a MONOCHROME2 mix-up would flip it).

  EXIT 0 all checks pass · 1 a check failed (or st2k/magick missing).
      pwsh scripts\check-dicom.ps1
#>
param([int]$Size = 120)
$ErrorActionPreference = 'Stop'

$st2k = Join-Path (& "$PSScriptRoot\_targetdir.ps1") 'release\st2k.exe'
if (-not (Test-Path $st2k)) { Write-Host "[dicom] st2k.exe not built" -ForegroundColor Red; exit 1 }
$magick = (Get-ChildItem 'C:\Program Files\ImageMagick*\magick.exe' -EA SilentlyContinue | Select-Object -First 1).FullName
if (-not $magick) { Write-Host "[dicom] ImageMagick not found — .dcm needs the magick tier; skipping check." -ForegroundColor Yellow; exit 0 }

$fix = Join-Path $PSScriptRoot '..\tests\fixtures\dicom'
$tmp = Join-Path $env:TEMP 'st2k-dicom-check'
New-Item -ItemType Directory -Force $tmp | Out-Null

# Sample one pixel as an [r,g,b] int array via a 1x1 crop. Parse the always-present
# #RRGGBB hex (works for both colour and single-channel gray txt output).
function Pixel($png, [int]$x, [int]$y) {
    $t = (& $magick $png -crop "1x1+$x+$y" -depth 8 txt:- 2>$null) -join "`n"
    $m = [regex]::Match($t, '#([0-9A-Fa-f]{6})')
    if (-not $m.Success) { throw "could not sample $png @ $x,$y : $t" }
    $h = $m.Groups[1].Value
    return @([Convert]::ToInt32($h.Substring(0,2),16), [Convert]::ToInt32($h.Substring(2,2),16), [Convert]::ToInt32($h.Substring(4,2),16))
}

$fail = 0
function Check($name, [bool]$ok, $detail) {
    if ($ok) { Write-Host ("[dicom]   OK  {0}  {1}" -f $name, $detail) -ForegroundColor Green }
    else     { Write-Host ("[dicom]  FAIL {0}  {1}" -f $name, $detail) -ForegroundColor Red; $script:fail++ }
}

# --- 1) colour stripes: hue preservation ------------------------------------
$colorIn = Join-Path $fix 'color_stripes.dcm'
$colorOut = Join-Path $tmp 'color.png'
& $st2k thumbnail $colorIn $colorOut --size $Size 2>$null | Out-Null
if (-not (Test-Path $colorOut)) { Write-Host "[dicom] FAIL color_stripes.dcm did not render" -ForegroundColor Red; exit 1 }
$W = [int](& $magick $colorOut -format '%w' info:); $H = [int](& $magick $colorOut -format '%h' info:)
$y = [int]($H/2)
# six stripe centres (unary comma keeps each [r,g,b] a single element, no flattening)
$px = @(); for ($i=0; $i -lt 6; $i++) { $px += ,(Pixel $colorOut ([int]($W*(2*$i+1)/12)) $y) }
$red,$grn,$blu,$gold,$gray,$dark = $px
Check 'red-dominant'   (($red[0]  -gt $red[1]+40)  -and ($red[0]  -gt $red[2]+40))  ("rgb=$($red -join ',')")
Check 'green-dominant' (($grn[1]  -gt $grn[0]+40)  -and ($grn[1]  -gt $grn[2]+40))  ("rgb=$($grn -join ',')")
Check 'blue-dominant'  (($blu[2]  -gt $blu[0]+40)  -and ($blu[2]  -gt $blu[1]+40))  ("rgb=$($blu -join ',')")
# GOLD = the hue-preservation canary: warm (R & G both well above B).
Check 'gold-warm'      (($gold[0] -gt $gold[2]+35) -and ($gold[1] -gt $gold[2]+25) -and ($gold[0] -ge $gold[1]-10)) ("rgb=$($gold -join ',')")
# GRAY = near-neutral (channels close together).
Check 'gray-neutral'   ((($gray | Measure-Object -Maximum).Maximum - ($gray | Measure-Object -Minimum).Minimum) -lt 40) ("rgb=$($gray -join ',')")
# DARK = the auto-level black anchor (dominant-lowest stripe).
Check 'dark-darkest'   ((($dark | Measure-Object -Maximum).Maximum) -lt ($gray | Measure-Object -Minimum).Minimum) ("rgb=$($dark -join ',')")

# --- 2) MONOCHROME1 inversion ----------------------------------------------
$monoIn = Join-Path $fix 'mono1_grad.dcm'
$monoOut = Join-Path $tmp 'mono1.png'
& $st2k thumbnail $monoIn $monoOut --size $Size 2>$null | Out-Null
if (-not (Test-Path $monoOut)) { Write-Host "[dicom] FAIL mono1_grad.dcm did not render" -ForegroundColor Red; exit 1 }
$Wm = [int](& $magick $monoOut -format '%w' info:); $Hm = [int](& $magick $monoOut -format '%h' info:)
$left  = Pixel $monoOut ([int]($Wm*0.08)) ([int]($Hm/2))
$right = Pixel $monoOut ([int]($Wm*0.92)) ([int]($Hm/2))
# MONOCHROME1: stored 0 (left) = WHITE, 255 (right) = BLACK -> left brighter.
Check 'mono1-inverted' ($left[0] -gt $right[0]+40) ("left=$($left[0]) right=$($right[0])")

if ($fail) { Write-Host ("[dicom] {0} check(s) FAILED — .dcm colour/contrast regressed." -f $fail) -ForegroundColor Red; exit 1 }
Write-Host "[dicom] all DICOM content checks passed." -ForegroundColor Green
exit 0
