<#
.SYNOPSIS
  Local pre-push gate. Mirrors the GitHub CI `build-test` + `deny` jobs so a broken
  push never has to round-trip through CI to be caught.

  Wired up as a git pre-push hook (.git/hooks/pre-push), but also runnable by hand:
      pwsh scripts/preflight.ps1

  These checks are RELEASE builds on purpose: the tree ships `panic="abort"` + `lto`,
  and some failures (e.g. link-time "unresolved external symbol") only surface in a
  release link — a debug `cargo test` would NOT catch them.
#>
$ErrorActionPreference = 'Stop'
$failed = $false

function Step([string]$name, [scriptblock]$block) {
    Write-Host ""
    Write-Host "==> $name" -ForegroundColor Cyan
    & $block
    if ($LASTEXITCODE -ne 0) {
        Write-Host "FAILED: $name (exit $LASTEXITCODE)" -ForegroundColor Red
        $script:failed = $true
    }
}

# ORDER THE CHEAP CHECKS FIRST. Rustfmt costs ~2 SECONDS and is the check a fresh edit is
# most likely to trip, yet it used to run near the END, behind three LTO release builds and
# two full test passes. On 2026-09-08 that cost a ~30-minute gate run to report one wrapped
# function signature, and then a second ~30-minute run to re-prove everything that had already
# passed. A gate that finds the cheapest failure last converts a two-second fix into an hour.
#
# The rule this encodes, and it generalises to any gate you add here: sort steps by
# (cost to run) ASCENDING, not by the order of the CI job being mirrored. CI runs its jobs in
# PARALLEL across runners, so its ordering carries no signal about what should block first on
# one machine. Anything that needs no build artifacts belongs above this line.
Step 'rustfmt (--check)' { cargo fmt --all --check }

# Mirror .github/workflows/ci.yml -> build-test job, in order. A bare default-feature
# `cargo build --release` (no -p split) used to stand in for this and NEVER built the
# dll/dlghook packages or the webp-lossy/html-preview/hdr-capture/dll-i18n-subset feature
# combinations CI gates on — a compile error reachable only under one of those passed here
# and only surfaced after a CI round-trip. `--locked` (matching CI) also means a stale
# Cargo.lock now fails the build directly here, same as it would in CI.
if (-not $failed) { Step 'build production EXEs' { cargo build --release --locked -p sagethumbs2k --features webp-lossy,html-preview,hdr-capture } }
if (-not $failed) { Step 'build production slim DLL' { cargo build --release --locked -p sagethumbs2k-dll --features webp-lossy,dll-i18n-subset } }
if (-not $failed) { Step 'build dialog hook DLL'      { cargo build --release --locked -p sagethumbs2k-dlghook } }
# Guard: a build that DID succeed can still have regenerated Cargo.lock in a way `--locked`
# let through (e.g. a lockfile-only change unrelated to what was just compiled) — if it now
# differs from the COMMITTED lock, the committed lock is stale. CI runs `cargo-deny --locked`
# and REJECTS that (this is exactly what broke the 0.8.0 release: the version bump landed in
# Cargo.toml but the lock update never got committed). Catch it here, before the push.
if (-not $failed) {
    Step 'Cargo.lock in sync with Cargo.toml' {
        git diff --quiet -- Cargo.lock
        if ($LASTEXITCODE -ne 0) {
            Write-Host "  Cargo.lock was regenerated by the build — your COMMITTED lock is STALE." -ForegroundColor Yellow
            Write-Host "  CI's cargo-deny --locked check will reject it. Fix: git add Cargo.lock, commit (or --amend), then re-push." -ForegroundColor Yellow
        }
    }
}
# CI's build-test job builds a DEBUG cdylib and runs the suite against IT. These two steps are
# that job, verbatim (ci.yml "Build debug test DLL" / "Unit and integration tests"), which is
# the whole reason they are here: this gate exists to catch what CI would catch, before the
# round trip. The COM integration tests LoadLibrary whichever cdylib sits in the profile
# directory they were built into, so the debug DLL built immediately above is the one they get.
#
# An earlier version of this comment justified the pairing by claiming debug and release differ
# behaviourally for the DLL, on the Media Foundation delay-load / video decode paths. MEASURED
# 2026-09-09, that is false for the test suite: `format_capability_claims` runs all 6 of its
# tests with nothing skipped in BOTH profiles. `video::media_foundation_available()` is a
# runtime LoadLibrary probe, identical either way, and src/build.rs applies /DELAYLOAD per-BIN,
# not per-profile. The CLAUDE.md 6.1 note that claim came from is about verify.ps1 rendering
# corpus samples through the debug st2k.exe, which is a different binary and a different
# question. Don't reintroduce the claim without re-measuring it.
if (-not $failed) { Step 'build debug test DLL (mirrors CI)' { cargo build --locked } }
if (-not $failed) { Step 'unit + integration tests, debug profile (mirrors CI)' { cargo test --locked --tests } }

# A SECOND, release-profile run of the same suite used to sit here and it cost ~8 minutes of
# every push. It now lives in `.github/workflows/release-profile-tests.yml` and runs as a GATE
# inside `release.ps1` at step [3b/6], dispatched and waited on.
#
# Moving it was not a downgrade. As a local step it ran only on the machine whose pre-push hook
# is installed, so a pull request, a push from another machine, and `main` itself were never
# covered - while being the only place the shipped-shape artifacts were tested at all. It now
# gates the release itself, which is the moment that coverage actually protects somebody, and
# it costs an ordinary push nothing. It is deliberately NOT a ci.yml job: a release-profile run
# is a full LTO build, and `test-architecture-release-contract.ps1` keeps per-push validation
# in the fast debug profile on purpose.
#
# The release BUILD steps above stay here, because a release-only link failure (panic="abort"
# + LTO, "unresolved external symbol") is worth catching before the push and costs seconds on
# a warm cache rather than minutes.
if (-not $failed) { Step 'clippy (-D warnings)'  { cargo clippy --release --all-targets -- -D warnings } }
# Rustfmt used to run HERE, and was missing entirely until 2026-08-05 (this gate printed
# "safe to push" on a commit CI then failed on formatting alone). It now runs FIRST, before
# any build — see the ordering note at the top for why, and what it cost to learn.

# Mirror the `deny` job — only if cargo-deny is installed locally (deny.toml at repo root).
# A missing tool used to fall straight through to "PREFLIGHT PASSED" with no printed line at
# all, so advisories/licenses/bans went unchecked on a machine that never noticed the gate was
# absent (docs/DEVELOPMENT_GOTCHAS.md names this exact failure class from a shipped incident).
if (-not $failed) {
    if (Get-Command cargo-deny -ErrorAction SilentlyContinue) {
        Step 'cargo-deny' { cargo deny check }
    } else {
        Write-Host ""
        Write-Host "==> cargo-deny" -ForegroundColor Cyan
        Write-Host "SKIPPED: cargo-deny is not installed (cargo install cargo-deny) — advisories, licenses and bans were NOT checked locally." -ForegroundColor Yellow
    }
}

Write-Host ""
if ($failed) {
    Write-Host "PREFLIGHT FAILED — push blocked. (bypass once with: git push --no-verify)" -ForegroundColor Red
    exit 1
}
Write-Host "PREFLIGHT PASSED — safe to push." -ForegroundColor Green
exit 0
