<#
.SYNOPSIS
  Local pre-push gate. Mirrors the GitHub CI `build-test` + `deny` jobs so a broken
  push never has to round-trip through CI to be caught.

  Wired up as a git pre-push hook (.git/hooks/pre-push), but also runnable by hand:
      pwsh scripts/preflight.ps1

  These checks are RELEASE builds on purpose: the tree ships `panic="abort"` + `lto`,
  and some failures (e.g. link-time "unresolved external symbol") only surface in a
  release link — a debug `cargo test` would NOT catch them.
#>
$ErrorActionPreference = 'Stop'
$failed = $false

function Step([string]$name, [scriptblock]$block) {
    Write-Host ""
    Write-Host "==> $name" -ForegroundColor Cyan
    & $block
    if ($LASTEXITCODE -ne 0) {
        Write-Host "FAILED: $name (exit $LASTEXITCODE)" -ForegroundColor Red
        $script:failed = $true
    }
}

# Mirror .github/workflows/ci.yml -> build-test job, in order. A bare default-feature
# `cargo build --release` (no -p split) used to stand in for this and NEVER built the
# dll/dlghook packages or the webp-lossy/html-preview/hdr-capture/dll-i18n-subset feature
# combinations CI gates on — a compile error reachable only under one of those passed here
# and only surfaced after a CI round-trip. `--locked` (matching CI) also means a stale
# Cargo.lock now fails the build directly here, same as it would in CI.
Step 'build production EXEs'        { cargo build --release --locked -p sagethumbs2k --features webp-lossy,html-preview,hdr-capture }
if (-not $failed) { Step 'build production slim DLL' { cargo build --release --locked -p sagethumbs2k-dll --features webp-lossy,dll-i18n-subset } }
if (-not $failed) { Step 'build dialog hook DLL'      { cargo build --release --locked -p sagethumbs2k-dlghook } }
# Guard: a build that DID succeed can still have regenerated Cargo.lock in a way `--locked`
# let through (e.g. a lockfile-only change unrelated to what was just compiled) — if it now
# differs from the COMMITTED lock, the committed lock is stale. CI runs `cargo-deny --locked`
# and REJECTS that (this is exactly what broke the 0.8.0 release: the version bump landed in
# Cargo.toml but the lock update never got committed). Catch it here, before the push.
if (-not $failed) {
    Step 'Cargo.lock in sync with Cargo.toml' {
        git diff --quiet -- Cargo.lock
        if ($LASTEXITCODE -ne 0) {
            Write-Host "  Cargo.lock was regenerated by the build — your COMMITTED lock is STALE." -ForegroundColor Yellow
            Write-Host "  CI's cargo-deny --locked check will reject it. Fix: git add Cargo.lock, commit (or --amend), then re-push." -ForegroundColor Yellow
        }
    }
}
# CI's build-test job additionally builds a DEBUG cdylib and runs tests against IT, not just
# the release binary - the release-only ladder above does not exercise that profile at all,
# despite this script's own header claiming to mirror that job. Debug and release are
# documented elsewhere in this repo as behaviorally different for the DLL (Media Foundation
# delay-load / video decode paths), and the COM integration tests LoadLibrary whichever cdylib
# was built last, so a push could go green here in release and still fail CI's debug leg. Run
# CI's own two steps, verbatim (ci.yml "Build debug test DLL" / "Unit and integration tests"),
# in ADDITION to the release ladder above rather than instead of it - the release-profile
# checks below stay, because release-only failures (e.g. panic=abort link errors) are real too.
if (-not $failed) { Step 'build debug test DLL (mirrors CI)' { cargo build --locked } }
if (-not $failed) { Step 'unit + integration tests, debug profile (mirrors CI)' { cargo test --locked --tests } }

# `--lib` is explicit and not left to ride along with `--tests`: ci.yml's own build-test job
# comment asserts `--tests` alone already covers library unit tests, but that reading is not
# how `--tests` is documented (it selects the integration-test targets under tests/, not the
# lib target) - and docs/TODO.md separately calls `cargo test --lib --bin SageThumbs2K` "the
# correct gate" for exactly the ~1190 #[test]s under src/. Passing both selectors here is
# correct under either reading, so this step no longer depends on resolving that disagreement.
if (-not $failed) { Step 'unit + integration tests (lib + tests)' { cargo test --release --lib --tests } }
if (-not $failed) { Step 'clippy (-D warnings)'  { cargo clippy --release --all-targets -- -D warnings } }
# Rustfmt was MISSING here until 2026-08-05, so this gate printed "safe to push" on a commit
# CI then failed on formatting alone. Cheap, and the last step of the job we claim to mirror.
if (-not $failed) { Step 'rustfmt (--check)'     { cargo fmt --all --check } }

# Mirror the `deny` job — only if cargo-deny is installed locally (deny.toml at repo root).
# A missing tool used to fall straight through to "PREFLIGHT PASSED" with no printed line at
# all, so advisories/licenses/bans went unchecked on a machine that never noticed the gate was
# absent (docs/DEVELOPMENT_GOTCHAS.md names this exact failure class from a shipped incident).
if (-not $failed) {
    if (Get-Command cargo-deny -ErrorAction SilentlyContinue) {
        Step 'cargo-deny' { cargo deny check }
    } else {
        Write-Host ""
        Write-Host "==> cargo-deny" -ForegroundColor Cyan
        Write-Host "SKIPPED: cargo-deny is not installed (cargo install cargo-deny) — advisories, licenses and bans were NOT checked locally." -ForegroundColor Yellow
    }
}

Write-Host ""
if ($failed) {
    Write-Host "PREFLIGHT FAILED — push blocked. (bypass once with: git push --no-verify)" -ForegroundColor Red
    exit 1
}
Write-Host "PREFLIGHT PASSED — safe to push." -ForegroundColor Green
exit 0
