//! Locale-table generation for the app's build script (`src/build.rs`).
//!
//! These functions were moved here **verbatim** out of `src/build.rs` so they can carry
//! unit tests: cargo never compiles a build script with `cfg(test)`, so a build script
//! cannot be tested. `generate_locales` — the orchestration that owns every `cargo:`
//! directive, plus the reads of `OUT_DIR` / `CARGO_FEATURE_DLL_I18N_SUBSET` — stays in
//! `src/build.rs` and calls into this module.
//!
//! A few functions below still emit `cargo:` directives themselves (`read_locales` prints a
//! `rerun-if-changed` per locale file; `append_locale_gap_report` and `write_coverage_file`
//! print `cargo:warning`). That is intentional and harmless: this code runs inside the
//! build-script process, so those directives still reach cargo.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::Path;

/// The single predicate for "a key the shell-extension DLL actually looks up": it only
/// ever calls `t()` with `menu_*` keys. Reused both to FILTER the emitted LOCALES table
/// (under the `dll-i18n-subset` feature) and to build the authoritative `DLL_KEYS` slice.
fn is_dll_key(k: &str) -> bool {
    k.starts_with("menu_")
}

/// Read and parse every `locales/<code>.toml` under `dir` into `{code: {key: value}}`.
/// Fails the build on an unreadable / malformed locale rather than silently shipping a
/// blank language.
pub fn read_locales(dir: &Path) -> BTreeMap<String, BTreeMap<String, String>> {
    let mut langs: BTreeMap<String, BTreeMap<String, String>> = BTreeMap::new();
    let Ok(entries) = std::fs::read_dir(dir) else {
        return langs;
    };
    for e in entries.flatten() {
        let path = e.path();
        if path.extension().and_then(|s| s.to_str()) != Some("toml") {
            continue;
        }
        let code = path.file_stem().unwrap().to_string_lossy().to_string();
        let text = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("locale {}: {e}", path.display()));
        let map: BTreeMap<String, String> = toml::from_str(&text)
            .unwrap_or_else(|e| panic!("locale {}: invalid TOML: {e}", path.display()));
        langs.insert(code, map);
        println!(
            "cargo:rerun-if-changed=assets/locales/{}",
            e.file_name().to_string_lossy()
        );
    }
    langs
}

/// Emit the `LOCALES` static: one `(code, &[(key, value)])` entry per locale, in `order`,
/// filtered to `menu_*` keys when `dll_subset` is set.
pub fn write_locales_table(
    out: &mut String,
    order: &[String],
    langs: &BTreeMap<String, BTreeMap<String, String>>,
    dll_subset: bool,
) {
    out.push_str("// @generated by build.rs from locales/*.toml — do not edit.\n");
    out.push_str("pub static LOCALES: &[(&str, &[(&str, &str)])] = &[\n");
    for code in order {
        let map = &langs[code];
        writeln!(out, "    ({:?}, &[", code).unwrap();
        for (k, v) in map {
            if dll_subset && !is_dll_key(k) {
                continue;
            }
            writeln!(out, "        ({:?}, {:?}),", k, v).unwrap();
        }
        out.push_str("    ]),\n");
    }
    out.push_str("];\n");
}

/// One locale's gap report against `en_keys`: appends `[code]` + its missing/extra keys
/// to `coverage` (and warns on the build log for genuinely-wrong EXTRA keys) when there
/// is anything to report, and tallies into `locales_with_gaps`/`total_fallbacks`.
fn append_locale_gap_report(
    coverage: &mut String,
    langs: &BTreeMap<String, BTreeMap<String, String>>,
    code: &str,
    en_keys: &BTreeSet<&String>,
    locales_with_gaps: &mut usize,
    total_fallbacks: &mut usize,
) {
    let keys: BTreeSet<&String> = langs[code].keys().collect();
    let missing: Vec<&&String> = en_keys.difference(&keys).collect();
    let extra: Vec<&&String> = keys.difference(en_keys).collect();
    if missing.is_empty() && extra.is_empty() {
        return;
    }
    *locales_with_gaps += 1;
    *total_fallbacks += missing.len();
    // Missing-key gaps are EXPECTED — those keys fall back to en at runtime (i18n.rs), so
    // they're recorded in i18n_coverage.txt rather than emitted as build warnings (they
    // were pure per-build noise). Only a genuinely-wrong EXTRA key — present in a locale
    // but not en.toml, i.e. a dead/typo'd string — still warns (normally fires zero).
    if !extra.is_empty() {
        println!(
            "cargo:warning=locale {code}: {} extra key(s) not in en.toml — dead strings (see i18n_coverage.txt)",
            extra.len(),
        );
    }
    writeln!(coverage, "[{code}]").unwrap();
    for m in &missing {
        writeln!(coverage, "    missing: {m}").unwrap();
    }
    for x in &extra {
        writeln!(coverage, "    extra:   {x}").unwrap();
    }
    coverage.push('\n');
}

/// Build the full `i18n_coverage.txt` text (every locale's missing/extra keys against
/// en.toml), or `None` when there is no `en` locale to validate against.
pub fn build_coverage_report(
    langs: &BTreeMap<String, BTreeMap<String, String>>,
    order: &[String],
) -> Option<String> {
    let en = langs.get("en")?;
    let en_keys: BTreeSet<&String> = en.keys().collect();
    let total = en_keys.len();
    let mut coverage = String::new();
    coverage.push_str("# i18n coverage report — @generated by build.rs\n");
    writeln!(
        coverage,
        "# en.toml is the canonical key set ({total} keys). Listed below are, per\n\
         # locale, the keys MISSING (fall back to en at runtime) and any EXTRA keys\n\
         # not in en.toml (dead strings). en-only keys falling back is intentional.\n",
    )
    .unwrap();

    let mut locales_with_gaps = 0usize;
    let mut total_fallbacks = 0usize;
    for code in order {
        if code == "en" {
            continue;
        }
        append_locale_gap_report(
            &mut coverage,
            langs,
            code,
            &en_keys,
            &mut locales_with_gaps,
            &mut total_fallbacks,
        );
    }

    if locales_with_gaps == 0 {
        coverage.push_str("All locales cover the full en.toml key set.\n");
    } else {
        // Headline tally goes in the coverage file, not the build log (silent build).
        writeln!(
            coverage,
            "\n# SUMMARY: {locales_with_gaps} locale(s) have gaps, {total_fallbacks} key fallback(s) total.",
        )
        .unwrap();
    }
    Some(coverage)
}

/// The `{name}` substitution slots in a locale value, in order of first appearance.
/// Same shape `scripts/check-locale-keys.ps1` compares (`\{[a-z_]+\}`).
fn placeholders(value: &str) -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    let mut rest = value;
    while let Some(start) = rest.find('{') {
        let after = &rest[start + 1..];
        match after.find('}') {
            Some(end)
                if end > 0
                    && after[..end]
                        .bytes()
                        .all(|b| b.is_ascii_lowercase() || b == b'_') =>
            {
                out.insert(after[..end].to_string());
                rest = &after[end + 1..];
            }
            _ => rest = after,
        }
    }
    out
}

/// FAIL THE BUILD unless every non-English locale carries exactly en.toml's key set with
/// the same placeholders. A missing key is a sentence shown in English inside another
/// language's UI; an extra key is a dead string; a dropped `{n}` is a sentence with a hole
/// in it at runtime. None of the three is allowed to compile (owner directive, Michael,
/// 2026-09-13). The message names the first few offenders per locale; the full list is one
/// `pwsh scripts/check-locale-keys.ps1` away, and `scripts/check-consistency.ps1` carries
/// the same rule for CI's consistency job.
pub fn enforce_locale_parity(langs: &BTreeMap<String, BTreeMap<String, String>>, order: &[String]) {
    let Some(en) = langs.get("en") else {
        return; // already warned above; nothing to compare against
    };
    let mut problems: Vec<String> = Vec::new();
    for code in order {
        if code == "en" {
            continue;
        }
        let loc = &langs[code];
        let missing: Vec<&str> = en
            .keys()
            .filter(|k| !loc.contains_key(*k))
            .map(String::as_str)
            .collect();
        let extra: Vec<&str> = loc
            .keys()
            .filter(|k| !en.contains_key(*k))
            .map(String::as_str)
            .collect();
        let slots: Vec<String> = en
            .iter()
            .filter_map(|(k, v)| {
                let theirs = loc.get(k)?;
                let want = placeholders(v);
                (!want.is_empty() && want != placeholders(theirs))
                    .then(|| format!("{k} (en has {want:?})"))
            })
            .collect();
        let first = |items: &[&str]| -> String {
            let shown: Vec<&str> = items.iter().take(5).copied().collect();
            let more = items.len().saturating_sub(shown.len());
            if more > 0 {
                format!("{} (+{more} more)", shown.join(", "))
            } else {
                shown.join(", ")
            }
        };
        if !missing.is_empty() {
            problems.push(format!(
                "locales/{code}.toml is MISSING {} key(s) that en.toml has: {}",
                missing.len(),
                first(&missing)
            ));
        }
        if !extra.is_empty() {
            problems.push(format!(
                "locales/{code}.toml has {} key(s) that en.toml does not: {}",
                extra.len(),
                first(&extra)
            ));
        }
        if !slots.is_empty() {
            let shown: Vec<&str> = slots.iter().map(String::as_str).collect();
            problems.push(format!(
                "locales/{code}.toml drops or invents a {{placeholder}} in {} key(s): {}",
                slots.len(),
                first(&shown)
            ));
        }
    }
    if !problems.is_empty() {
        panic!(
            "\n\nLOCALE PARITY FAILED - every en.toml key must exist in ALL locales with the same \
             {{placeholders}} (Michael, 2026-09-13: \"we absolutely cannot have any languages \
             missing strings\"). Add the missing translations to every file (a Sonnet fan-out \
             producing JSON, applied with one CRLF-safe script, is the shape) - never leave a key \
             en-only.\n  {}\n\nFull report: pwsh scripts/check-locale-keys.ps1\n",
            problems.join("\n  ")
        );
    }
}

/// Write the coverage report to `$OUT_DIR/i18n_coverage.txt`, if `OUT_DIR` is set.
pub fn write_coverage_file(coverage: &str) {
    if let Some(out_dir) = std::env::var_os("OUT_DIR") {
        let cov_path = Path::new(&out_dir).join("i18n_coverage.txt");
        if let Err(e) = std::fs::write(&cov_path, coverage) {
            println!("cargo:warning=i18n: couldn't write i18n_coverage.txt: {e}");
        }
    }
}

/// Emit `pub mod keys { pub const BTN_OK: &str = "btn_ok"; ... }`, one const per en.toml key.
pub fn write_keys_module(out: &mut String, langs: &BTreeMap<String, BTreeMap<String, String>>) {
    out.push_str(
        "\n/// Compile-time key constants generated from en.toml (the canonical key set).\n",
    );
    out.push_str("/// Use `keys::BTN_OK` instead of the bare string so a typo fails to compile.\n");
    out.push_str("pub mod keys {\n");
    if let Some(en) = langs.get("en") {
        for k in en.keys() {
            writeln!(out, "    pub const {}: &str = {:?};", to_upper_snake(k), k).unwrap();
        }
    }
    out.push_str("}\n");
}

/// Emit `pub static DLL_KEYS: &[&str]`, the `menu_*` subset of en.toml's keys.
pub fn write_dll_keys(out: &mut String, langs: &BTreeMap<String, BTreeMap<String, String>>) {
    out.push_str("\n/// Keys the shell-extension DLL actually looks up (the `menu_*` set).\n");
    out.push_str(
        "/// Under the `dll-i18n-subset` feature the LOCALES table is filtered to exactly\n",
    );
    out.push_str("/// these keys; without it the full table ships (the EXE/CLI path).\n");
    out.push_str("pub static DLL_KEYS: &[&str] = &[\n");
    if let Some(en) = langs.get("en") {
        for k in en.keys().filter(|k| is_dll_key(k)) {
            writeln!(out, "    {k:?},").unwrap();
        }
    }
    out.push_str("];\n");
}

/// `btn_ok` -> `BTN_OK`, `pt-BR`-style keys never occur (keys are snake_case),
/// but any non-alphanumeric is mapped to `_` defensively so the output is always
/// a valid Rust identifier.
fn to_upper_snake(key: &str) -> String {
    key.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn build_langs(
        pairs: &[(&str, &[(&str, &str)])],
    ) -> BTreeMap<String, BTreeMap<String, String>> {
        pairs
            .iter()
            .map(|(code, kv)| {
                (
                    (*code).to_string(),
                    kv.iter()
                        .map(|(k, v)| ((*k).to_string(), (*v).to_string()))
                        .collect(),
                )
            })
            .collect()
    }

    fn build_order(codes: &[&str]) -> Vec<String> {
        codes.iter().map(|c| (*c).to_string()).collect()
    }

    /// Digits and underscores survive; any other byte maps to `_`.
    #[test]
    fn to_upper_snake_maps_digits_and_underscores() {
        assert_eq!(to_upper_snake("btn_ok"), "BTN_OK");
        assert_eq!(to_upper_snake("dlg_err2_text"), "DLG_ERR2_TEXT");
        assert_eq!(to_upper_snake("a.b-c"), "A_B_C");
    }

    /// No brace -> empty; one slot -> that slot; a repeated slot is de-duplicated; an
    /// uppercase/malformed or unclosed slot is ignored (the same `\{[a-z_]+\}` shape the
    /// PowerShell checker uses).
    #[test]
    fn placeholders_handles_plain_single_repeated_and_malformed() {
        assert!(placeholders("no slots here").is_empty());
        assert_eq!(
            placeholders("hello {name}"),
            BTreeSet::from(["name".to_string()])
        );
        assert_eq!(
            placeholders("{n} of {n}"),
            BTreeSet::from(["n".to_string()])
        );
        assert!(placeholders("{NOPE}").is_empty());
        assert!(placeholders("unclosed {name").is_empty());
    }

    #[test]
    fn is_dll_key_matches_only_menu_keys() {
        assert!(is_dll_key("menu_open"));
        assert!(!is_dll_key("btn_ok"));
        assert!(!is_dll_key("menu")); // the trailing underscore is required
    }

    #[test]
    fn enforce_locale_parity_accepts_a_matching_set() {
        let langs = build_langs(&[
            ("en", &[("a", "x"), ("b", "y {n}")]),
            ("fr", &[("a", "X"), ("b", "Y {n}")]),
        ]);
        enforce_locale_parity(&langs, &build_order(&["en", "fr"]));
    }

    #[test]
    #[should_panic(expected = "LOCALE PARITY FAILED")]
    fn enforce_locale_parity_panics_on_a_missing_key() {
        let langs = build_langs(&[("en", &[("a", "x"), ("b", "y")]), ("fr", &[("a", "X")])]);
        enforce_locale_parity(&langs, &build_order(&["en", "fr"]));
    }

    /// A two-language map with a gap: `fr` is missing `b`, and the report both names the
    /// locale + key and tallies the fallback.
    #[test]
    fn build_coverage_report_lists_a_gap() {
        let langs = build_langs(&[("en", &[("a", "x"), ("b", "y")]), ("fr", &[("a", "X")])]);
        let report = build_coverage_report(&langs, &build_order(&["en", "fr"])).unwrap();
        assert!(report.contains("[fr]"), "{report}");
        assert!(report.contains("missing: b"), "{report}");
        assert!(
            report.contains("1 locale(s) have gaps, 1 key fallback(s) total"),
            "{report}"
        );
    }

    /// Two real `.toml` files under a temp dir, parsed and cleaned up.
    #[test]
    fn read_locales_parses_two_toml_files() {
        let dir =
            std::env::temp_dir().join(format!("build_support_locales_{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("en.toml"), "a = \"1\"\nb = \"2\"\n").unwrap();
        std::fs::write(dir.join("de.toml"), "a = \"eins\"\n").unwrap();

        let parsed = read_locales(&dir);

        std::fs::remove_dir_all(&dir).unwrap();
        assert_eq!(parsed.len(), 2);
        assert_eq!(parsed["en"]["a"], "1");
        assert_eq!(parsed["en"]["b"], "2");
        assert_eq!(parsed["de"]["a"], "eins");
        assert!(!parsed["de"].contains_key("b"));
    }
}
