//! Format corner-badges: stamp the file's format (`PSD`, `JXL`, `AVIF`…) onto the thumbnail.
//!
//! Requested for 1.7.6: in a folder of visually similar images you cannot tell a PSD from a
//! JPEG, because a thumbnail shows the picture and says nothing about the container.
//!
//! Off by default (`FormatBadge`), because it MODIFIES the picture the user asked to see —
//! an opt-in decoration, never a surprise.
//!
//! # Why letter outlines drawn with tiny-skia, and not GDI text or a pixel font
//!
//! This runs inside `explorer.exe`'s thumbnail worker, on any machine, under any locale and
//! any DPI. `DrawText` would drag in a device context, font selection, and the user's font
//! substitution settings — three things that differ per machine and would make the badge
//! render differently (or fail) depending on who is looking. So the letters are outlines
//! compiled in as data ([`font`], DejaVu Sans Condensed Bold, generated by
//! `scripts/build-badge-font.py`) and filled with tiny-skia, which the SVG thumbnails already
//! link: byte-identical everywhere, no GDI object, nothing that can fail.
//!
//! Until 3.4.1 the letters were a 5x7 pixel font scaled by a whole number. Explorer shows the
//! 256 px tile at its own size (144 px at 150 % scaling), and a pixel font resized by 0.56 came
//! out jagged and blurry at once (issue #50). Anti-aliased outlines at the exact size the badge
//! needs survive that resize the way any lettering in a photo does.
//!
//! # Sized by the tile, not by the picture's shape
//!
//! Explorer fits a thumbnail's LONG side to the tile it shows, so the long side is the one
//! measure every tile of a folder shares. The badge used to follow the SHORT side: a square
//! picture got twice the badge of a 16:9 frame or a portrait cover in the same folder (issue
//! #50: ZIP and a square WEBP large, MP4, EPUB and a wide WEBP small).

mod font;

/// The user's style and size for the mark live with the other settings (both are stored
/// DWORDs); this module only reads them, so the drawing code stays a pure function of
/// (image, label, style, size, frame).
use st2k_base::settings::{BadgeSize, BadgeStyle};
use tiny_skia::{FillRule, Paint, Path, PathBuilder, Pixmap, Stroke, Transform};

/// Longest label we will draw. Keeps the badge from eating the tile on a silly extension.
const MAX_LABEL: usize = 5;

/// A thumbnail whose long side is under this gets NO badge: below ~64px the label would
/// cover a meaningful share of the image and be unreadable anyway. Explorer's smallest tile
/// is 16px.
const MIN_BADGED_EDGE: u32 = 64;

/// The smallest cap height, in pixels of the returned bitmap, that still reads as letters. A
/// badge that would come out smaller is drawn at this size, or not at all when that no longer
/// fits the tile.
const MIN_CAP_PX: f32 = 7.0;

/// What Explorer draws OVER the edges of a tile, as fractions of the tile, so the badge can
/// sit clear of it.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct Frame {
    /// Covered at each side, as a fraction of the width.
    pub side: f32,
    /// Covered at the bottom, as a fraction of the height.
    pub bottom: f32,
}

impl Frame {
    /// Nothing drawn over the tile.
    pub const NONE: Frame = Frame {
        side: 0.0,
        bottom: 0.0,
    };

    /// The edges Explorer covers on the tile of `ext`, a `w` x `h` thumbnail.
    ///
    /// Explorer draws a film strip over every LANDSCAPE video tile (a type whose
    /// `PerceivedType` is `video`, which `register` writes for our whole video category).
    /// Measured 2026-10-01 off `PrintWindow` captures at 96 and 256 px tiles (issue #51): the
    /// sprocket strips cover 12.1-12.4 % of the tile's width on each side and a dark rim about
    /// 5 % of its height at the top and bottom, laid over the picture rather than beside it.
    /// Square and portrait videos get no strip. The margins below carry a little to spare.
    pub fn explorer_draws_over(ext: &str, w: u32, h: u32) -> Frame {
        let video = st2k_base::formats::category(&ext.to_ascii_lowercase())
            == st2k_base::formats::Category::Video;
        if video && w > h {
            Frame {
                side: 0.13,
                bottom: 0.055,
            }
        } else {
            Frame::NONE
        }
    }
}

/// The category tint for an extension, as (r, g, b).
///
/// Seven hues, one per [`st2k_base::formats::Category`], picked to stay apart from each other at
/// badge size (roughly 20 px across on a 256 px tile) and to read on both light and dark
/// thumbnails. They are NOT theme-aware on purpose: the badge is burned into the bitmap the
/// shell caches, so it cannot follow a theme the user changes later.
fn category_rgb(ext: &str) -> (u8, u8, u8) {
    use st2k_base::formats::Category;
    match st2k_base::formats::category(ext) {
        Category::Image => (36, 116, 208),   // blue
        Category::Raw => (124, 77, 200),     // violet
        Category::Ebook => (32, 140, 84),    // green
        Category::Document => (196, 60, 52), // red
        Category::Audio => (0, 138, 148),    // teal
        Category::Video => (176, 52, 132),   // magenta
        Category::Archive => (90, 96, 110),  // slate
    }
}

/// Scale each channel by `n/255`, for the darker rim of a tint (`n` < 255).
fn shade(rgb: (u8, u8, u8), n: u32) -> (u8, u8, u8) {
    let f = |c: u8| ((c as u32 * n) / 255).min(255) as u8;
    (f(rgb.0), f(rgb.1), f(rgb.2))
}

/// Mix `rgb` toward white by `n/255`. Used for the dog-ear flap: multiplying a tint UP
/// saturates the already-large channel and shifts the hue, while mixing toward white keeps
/// the hue and just lightens it, which is what "the back of the sheet" should look like.
fn blend_to_white(rgb: (u8, u8, u8), n: u32) -> (u8, u8, u8) {
    let f = |c: u8| (c as u32 + (255 - c as u32) * n / 255).min(255) as u8;
    (f(rgb.0), f(rgb.1), f(rgb.2))
}

/// The label to stamp for a file name, or `None` when there is nothing sensible to draw.
///
/// Uppercased, `.`-stripped, and limited to characters the font has. A name with no
/// extension, or an extension too long or full of unrenderable characters, gets no badge
/// rather than a mangled one.
pub fn label_for(file_name: &str) -> Option<String> {
    let ext = file_name.rsplit_once('.')?.1;
    if ext.is_empty() || ext.len() > MAX_LABEL {
        return None;
    }
    let up: String = ext.to_ascii_uppercase();
    if !up.bytes().all(|b| font::glyph(b).is_some()) {
        return None;
    }
    Some(up)
}

/// Stamp `label` into the bottom-right of an RGBA8 image, in place.
///
/// Drawn as a dark rounded chip with light text: a bare glyph would vanish against matching
/// image content, and a thumbnail is arbitrary content by definition. The chip is
/// alpha-blended rather than overwritten so it reads as an overlay.
///
/// [`BadgeStyle::Icon`] keeps all of that and adds the category tint + dog-eared page
/// silhouette; the geometry is shared so the two styles can never drift apart in size or
/// position. `frame` is what Explorer will draw over the tile's edges
/// ([`Frame::explorer_draws_over`]); the badge sits inside it.
///
/// No-ops on images too small to badge legibly, or when the label does not fit.
pub fn stamp(
    rgba: &mut [u8],
    w: u32,
    h: u32,
    label: &str,
    style: BadgeStyle,
    size: BadgeSize,
    frame: Frame,
) {
    let Some(g) = badge_geometry(w, h, label, style, size, frame) else {
        return; // too small to badge legibly, or the chip would not fit
    };
    // The label's own category decides the tint. `label` is the uppercased extension, and
    // `formats::category` matches lowercase tables, so fold the case back down here.
    let tint = category_rgb(&label.to_ascii_lowercase());
    let Some(chip) = render_chip(&g, label, tint, style) else {
        return;
    };
    composite(rgba, w, h, &chip, g.x0, g.y0);
}

/// The badge chip's geometry, in pixels of the thumbnail, keyed off the tile and the label so
/// the same numbers back the chip, the fold and the letters.
#[derive(Debug)]
struct BadgeGeom {
    /// Cap height of the letters.
    cap: f32,
    /// Font units to pixels.
    scale: f32,
    pad_x: f32,
    pad_y: f32,
    fold: f32,
    /// Extra advance between letters, in pixels.
    tracking: f32,
    chip_w: u32,
    chip_h: u32,
    x0: u32,
    y0: u32,
}

/// Advance width of `label` in font units, without tracking. Every character is known to
/// [`font`] (`label_for` refuses the rest); an unknown one counts as nothing.
fn label_units(label: &str) -> f32 {
    label
        .bytes()
        .filter_map(font::glyph)
        .map(|g| g.advance as f32)
        .sum()
}

/// Compute the chip's geometry, or `None` when the image is too small to badge legibly or
/// the chip would not fit.
fn badge_geometry(
    w: u32,
    h: u32,
    label: &str,
    style: BadgeStyle,
    size: BadgeSize,
    frame: Frame,
) -> Option<BadgeGeom> {
    if w.max(h) < MIN_BADGED_EDGE || label.is_empty() {
        return None;
    }
    // Cap height as a share of the LONG side (see the module doc), with a floor so a small
    // tile still gets letters that read.
    let wanted = (w.max(h) as f32 * size.cap_fraction()).max(MIN_CAP_PX);
    // The room left once Explorer's film strip (both sides) and rim (top and bottom) are
    // taken off. The badge keeps its size wherever it fits, so every tile of a folder shows
    // the same mark; it only shrinks on a tile too narrow for it, and never takes more than
    // half the height: an annotation, never a takeover.
    let room_w = w as f32 * (1.0 - 2.0 * frame.side);
    let room_h = h as f32 * (1.0 - 2.0 * frame.bottom);
    let at = |cap: f32| layout(cap, label, style);
    let (cw, ch) = at(wanted);
    let margin_at = |cap: f32| cap * 0.32;
    let shrink = ((room_w - 2.0 * margin_at(wanted)) / cw)
        .min(room_h * 0.5 / ch)
        .min(1.0);
    let cap = wanted * shrink;
    if cap < MIN_CAP_PX {
        return None; // would dominate the tile at any legible size: better to draw nothing
    }
    let (cw, ch) = at(cap);
    let pad_y = margin_at(cap);
    let margin = pad_y;
    let (chip_w, chip_h) = (cw.ceil() as u32, ch.ceil() as u32);
    let right = w as f32 * (1.0 - frame.side) - margin;
    let bottom = h as f32 * (1.0 - frame.bottom) - margin;
    if (chip_w as f32) > right || (chip_h as f32) > bottom {
        return None;
    }
    Some(BadgeGeom {
        cap,
        scale: cap / font::CAP_HEIGHT,
        pad_x: cap * 0.42,
        pad_y,
        fold: fold_for(cap, style),
        tracking: cap * 0.06,
        chip_w,
        chip_h,
        x0: (right - chip_w as f32).floor() as u32,
        y0: (bottom - chip_h as f32).floor() as u32,
    })
}

/// The dog-ear's leg for the icon style, or 0 for the plain chip.
fn fold_for(cap: f32, style: BadgeStyle) -> f32 {
    if style == BadgeStyle::Icon {
        cap * 0.45
    } else {
        0.0
    }
}

/// The chip's (width, height) for letters of cap height `cap`: the text, the padding, and
/// for the icon style an extra column on the right so the dog-ear never lands on a letter.
fn layout(cap: f32, label: &str, style: BadgeStyle) -> (f32, f32) {
    let scale = cap / font::CAP_HEIGHT;
    let n = label.len() as f32;
    let text_w = label_units(label) * scale + (n - 1.0).max(0.0) * cap * 0.06;
    let w = text_w + 2.0 * cap * 0.42 + fold_for(cap, style);
    let h = cap + 2.0 * cap * 0.32;
    (w, h)
}

/// A filled path's paint: solid `rgb` at alpha `a`, anti-aliased.
fn paint(rgb: (u8, u8, u8), a: u8) -> Paint<'static> {
    let mut p = Paint::default();
    p.set_color_rgba8(rgb.0, rgb.1, rgb.2, a);
    p.anti_alias = true;
    p
}

/// The chip outline: a rounded rectangle, with its top-right corner cut off along the fold
/// for the icon style.
fn chip_path(w: f32, h: f32, r: f32, fold: f32) -> Option<Path> {
    let mut pb = PathBuilder::new();
    pb.move_to(r, 0.0);
    if fold > 0.0 {
        pb.line_to(w - fold, 0.0);
        pb.line_to(w, fold);
    } else {
        pb.line_to(w - r, 0.0);
        pb.quad_to(w, 0.0, w, r);
    }
    pb.line_to(w, h - r);
    pb.quad_to(w, h, w - r, h);
    pb.line_to(r, h);
    pb.quad_to(0.0, h, 0.0, h - r);
    pb.line_to(0.0, r);
    pb.quad_to(0.0, 0.0, r, 0.0);
    pb.close();
    pb.finish()
}

/// The folded-back flap of the icon style's page.
fn flap_path(w: f32, fold: f32) -> Option<Path> {
    let mut pb = PathBuilder::new();
    pb.move_to(w - fold, 0.0);
    pb.line_to(w - fold, fold);
    pb.line_to(w, fold);
    pb.close();
    pb.finish()
}

/// `label`'s outlines in chip coordinates: left-aligned after the padding, sitting on the
/// baseline under the top padding.
fn text_path(g: &BadgeGeom, label: &str) -> Option<Path> {
    let mut pb = PathBuilder::new();
    let mut pen = g.pad_x;
    let baseline = g.pad_y + g.cap;
    for c in label.bytes() {
        let Some(glyph) = font::glyph(c) else {
            continue;
        };
        let at = |x: i16, y: i16| (pen + x as f32 * g.scale, baseline - y as f32 * g.scale);
        for seg in glyph.segs {
            match *seg {
                font::Seg::M(x, y) => {
                    let (x, y) = at(x, y);
                    pb.move_to(x, y);
                }
                font::Seg::L(x, y) => {
                    let (x, y) = at(x, y);
                    pb.line_to(x, y);
                }
                font::Seg::Q(cx, cy, x, y) => {
                    let (cx, cy) = at(cx, cy);
                    let (x, y) = at(x, y);
                    pb.quad_to(cx, cy, x, y);
                }
                font::Seg::Z => pb.close(),
            }
        }
        pen += glyph.advance as f32 * g.scale + g.tracking;
    }
    pb.finish()
}

/// Draw the whole badge into its own premultiplied pixmap, `chip_w` x `chip_h`.
fn render_chip(
    g: &BadgeGeom,
    label: &str,
    tint: (u8, u8, u8),
    style: BadgeStyle,
) -> Option<Pixmap> {
    let mut pm = Pixmap::new(g.chip_w, g.chip_h)?;
    let (w, h) = (g.chip_w as f32, g.chip_h as f32);
    let id = Transform::identity();
    let chip = chip_path(w, h, h * 0.2, g.fold)?;
    match style {
        // Near-black at ~72% so the underlying image still shows through slightly.
        BadgeStyle::Text => pm.fill_path(
            &chip,
            &paint((16, 16, 16), 184),
            FillRule::Winding,
            id,
            None,
        ),
        BadgeStyle::Icon => {
            pm.fill_path(&chip, &paint(tint, 235), FillRule::Winding, id, None);
            // A darker rim keeps the mark legible on a same-coloured picture.
            let rim = Stroke {
                width: (g.cap * 0.1).max(1.0),
                ..Stroke::default()
            };
            pm.stroke_path(&chip, &paint(shade(tint, 150), 255), &rim, id, None);
            if let Some(flap) = flap_path(w, g.fold) {
                // The folded-back flap: lighter, so it reads as the sheet's underside.
                pm.fill_path(
                    &flap,
                    &paint(blend_to_white(tint, 150), 245),
                    FillRule::Winding,
                    id,
                    None,
                );
                pm.stroke_path(&flap, &paint(shade(tint, 150), 255), &rim, id, None);
            }
        }
    }
    // Near-white and fully opaque for maximum contrast against the chip.
    if let Some(text) = text_path(g, label) {
        pm.fill_path(
            &text,
            &paint((245, 245, 245), 255),
            FillRule::Winding,
            id,
            None,
        );
    }
    Some(pm)
}

/// Source-over the premultiplied `chip` onto the straight-alpha `rgba` at `(x0, y0)`. The
/// thumbnail's own alpha is raised toward opaque where the chip covers it, so a badge on a
/// transparent PNG still reads instead of blending into whatever sits behind the icon.
fn composite(rgba: &mut [u8], w: u32, h: u32, chip: &Pixmap, x0: u32, y0: u32) {
    let cw = chip.width();
    for (i, src) in chip.pixels().iter().enumerate() {
        let a = src.alpha() as u32;
        if a == 0 {
            continue;
        }
        let (x, y) = (x0 + i as u32 % cw, y0 + i as u32 / cw);
        if x >= w || y >= h {
            continue;
        }
        let at = ((y * w + x) * 4) as usize;
        let Some(px) = rgba.get_mut(at..at + 4) else {
            continue;
        };
        let da = px[3] as u32;
        // Straight destination to premultiplied, blend, back to straight.
        let out_a = a + da * (255 - a) / 255;
        let mix = |s: u8, d: u8| {
            let premul = s as u32 + (d as u32 * da / 255) * (255 - a) / 255;
            (premul * 255 / out_a.max(1)).min(255) as u8
        };
        px[0] = mix(src.red(), px[0]);
        px[1] = mix(src.green(), px[1]);
        px[2] = mix(src.blue(), px[2]);
        px[3] = out_a.min(255) as u8;
    }
}

#[cfg(test)]
mod tests;

#[cfg(test)]
mod visual;
